ALTER TABLE upgrade_prompts 
ADD COLUMN IF NOT EXISTS shown_at TIMESTAMPTZ DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS clicked_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS converted_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS dismissed BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS dismissed_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}',
ADD COLUMN IF NOT EXISTS prompt_location VARCHAR(100);
