import { NextResponse } from 'next/server';
import { routeAIRequest, getAvailableProviders } from '@/services/aiRouter';

export const runtime = 'nodejs';

/**
 * AI Lead Generation API Route
 * Now uses smart routing: Anthropic (Claude) → OpenAI (GPT-4) → Gemini
 * Automatically falls back if primary provider fails
 */
export async function POST(req: Request) {
    try {
        console.log("[Lead Gen] Checking available AI providers...");
        const providers = getAvailableProviders();
        console.log("[Lead Gen] Available providers:", providers);

        const { industry, location } = await req.json();

        if (!industry || !location) {
            return NextResponse.json({ error: 'Industry and location are required' }, { status: 400 });
        }

        console.log(`[Lead Gen] Generating leads for: ${industry} in ${location}`);

        // Create lead generation prompt
        const prompt = `Generate EXACTLY 5 realistic and professional business leads for the "${industry}" industry in "${location}".

CRITICAL REQUIREMENTS:
- All data must be plausible and realistic for ${location}
- Business names must be appropriate for ${industry} industry
- Phone numbers must follow standard ${location} format
- Email addresses must be professional and realistic
- Facebook handles should be lowercase, no spaces
- DO NOT fabricate real companies - create plausible fictional ones
- DO NOT use placeholder data like "example.com" or "123-456-7890"

Return ONLY a valid JSON array (no markdown, no explanation) where each object has:
- id: random 8-character alphanumeric string
- businessName: realistic business name (not a real company)
- industry: "${industry}"
- location: "${location}"
- phone: realistic phone number for ${location}
- email: professional email (firstname@businessname.com format)
- facebook: lowercase handle
- estimatedValue: number between 5000-50000

Example format (DO NOT copy these exact values):
[{"id":"abc12345","businessName":"Tech Innovations LLC","industry":"${industry}","location":"${location}","phone":"(555) 123-4567","email":"contact@techinnovations.com","facebook":"techinnovations","estimatedValue":25000}]`;

        // Use smart router with fallback chain
        const response = await routeAIRequest({
            prompt,
            maxTokens: 2000,
            temperature: 0.8, // More creative for varied leads
        });

        console.log(`[Lead Gen] ✓ Generated by ${response.provider} (${response.model})`);

        // Parse JSON response
        let leads;
        try {
            // Clean response of markdown code blocks if present
            const cleanedContent = response.content
                .replace(/```json\n?/g, '')
                .replace(/```\n?/g, '')
                .trim();

            leads = JSON.parse(cleanedContent);

            // Validate leads format
            if (!Array.isArray(leads)) {
                throw new Error('Response is not an array');
            }
        } catch (parseError: any) {
            console.error('[Lead Gen] Failed to parse JSON:', parseError);
            console.error('[Lead Gen] Raw response:', response.content);
            return NextResponse.json({
                error: 'Failed to parse AI response. Please try again.',
                details: parseError.message
            }, { status: 500 });
        }

        return NextResponse.json({
            leads,
            provider: response.provider,
            model: response.model
        });
    } catch (error: any) {
        console.error('Lead Generation API Error:', error);
        return NextResponse.json({
            error: error.message || 'Failed to generate leads'
        }, { status: 500 });
    }
}
