import { NextResponse } from 'next/server';
import { routeAIRequest, getAvailableProviders } from '@/services/aiRouter';

export const runtime = 'nodejs';

/**
 * AI Lead Generation API Route
 * Now uses smart routing: Anthropic (Claude) → OpenAI (GPT-4) → Gemini
 * Automatically falls back if primary provider fails
 */
export async function POST(req: Request) {
    try {
        console.log("[Lead Gen] Checking available AI providers...");
        const providers = getAvailableProviders();
        console.log("[Lead Gen] Available providers:", providers);

        const { industry, location } = await req.json();

        if (!industry || !location) {
            return NextResponse.json({ error: 'Industry and location are required' }, { status: 400 });
        }

        console.log(`[Lead Gen] Generating leads for: ${industry} in ${location}`);

        // Create lead generation prompt
        const prompt = `Generate EXACTLY 5 high-quality, realistic business leads for the following specification:
Target Service/Industry: "${industry}"
Location: "${location}"

CRITICAL REQUIREMENTS:
- Match the SPECIFIC service description if provided (e.g., if industry is "Emergency Plumber", don't just return general contractors).
- All data must be plausible and realistic for ${location}.
- Business names must be creative and professional (fictional, but sounding like real local businesses).
- Phone numbers must follow standard ${location} format.
- Email addresses must be professional (e.g., info@businessname.com or contact@...).
- Facebook handles should be lowercase, simple, and relevant to the business name.
- DO NOT use placeholder names like "Company A" or "John Doe Inc".
- Return ONLY valid JSON.

Return a JSON array of objects with these keys:
- id: random 8-character string
- businessName: string
- industry: "${industry}"
- location: "${location}"
- phone: string
- email: string
- website: plausible website URL (fictional)
- facebook: string (handle only)
- estimatedValue: number (5000-50000)
- notes: A brief 1-sentence AI analysis of why this lead is a good fit for ${industry}.`;

        // Use smart router with fallback chain
        const response = await routeAIRequest({
            prompt,
            maxTokens: 2000,
            temperature: 0.8, // More creative for varied leads
        });

        console.log(`[Lead Gen] ✓ Generated by ${response.provider} (${response.model})`);

        // Parse JSON response
        let leads;
        try {
            // Clean response of markdown code blocks if present
            const cleanedContent = response.content
                .replace(/```json\n?/g, '')
                .replace(/```\n?/g, '')
                .trim();

            leads = JSON.parse(cleanedContent);

            // Validate leads format
            if (!Array.isArray(leads)) {
                throw new Error('Response is not an array');
            }
        } catch (parseError: any) {
            console.error('[Lead Gen] Failed to parse JSON:', parseError);
            console.error('[Lead Gen] Raw response:', response.content);
            return NextResponse.json({
                error: 'Failed to parse AI response. Please try again.',
                details: parseError.message
            }, { status: 500 });
        }

        return NextResponse.json({
            leads,
            provider: response.provider,
            model: response.model
        });
    } catch (error: any) {
        console.error('Lead Generation API Error:', error);
        return NextResponse.json({
            error: error.message || 'Failed to generate leads'
        }, { status: 500 });
    }
}
