'use client';
import {useEffect,useState} from 'react';
import {SERVICES,type Evidence} from '@/lib/platform-monitoring/model';
export default function MonitoringAdmin(){
 const [checks,setChecks]=useState<Evidence[]>([]);const [success,setSuccess]=useState<{service_name:string;checked_at:string}[]>([]);const [error,setError]=useState('');
 useEffect(()=>{let active=true;const controller=new AbortController();async function load(){try{const r=await fetch('/api/admin/platform-monitoring',{cache:'no-store',signal:controller.signal});if(!r.ok)throw new Error('Admin monitoring unavailable');const p=await r.json();if(active){setChecks(p.checks);setSuccess(p.last_successful);setError('');}}catch{if(active)setError('Admin monitoring unavailable');}}void load();const id=setInterval(load,30000);return()=>{active=false;controller.abort();clearInterval(id);};},[]);
 return <main className="min-h-screen bg-white p-5 text-slate-900 sm:p-10"><h1 className="text-2xl font-semibold">Platform monitoring</h1>{error&&<p role="alert">{error}</p>}
 {SERVICES.map(([id,name])=>{const rows=checks.filter(c=>c.service_name===id).reverse();const max=Math.max(1,...rows.map(c=>c.latency_ms||0));return <section key={id} className="my-8 border-t border-slate-200 pt-5"><h2 className="text-lg font-medium">{name}</h2><p className="text-sm">Last successful check: {success.find(s=>s.service_name===id)?.checked_at||'None recorded'}</p><svg viewBox="0 0 500 80" role="img" aria-label={`${name} response time graph, maximum ${max} ms`} className="my-3 h-20 w-full max-w-xl"><polyline fill="none" stroke="currentColor" strokeWidth="2" points={rows.map((r,i)=>`${i*500/Math.max(1,rows.length-1)},${75-(r.latency_ms||0)*70/max}`).join(' ')}/></svg><p className="text-xs">Response time, 0–{max} ms; recent 500 checks across all services</p><div className="overflow-x-auto"><table className="mt-3 w-full text-left text-sm"><thead><tr><th>Checked</th><th>Status</th><th>Latency</th><th>Evidence</th></tr></thead><tbody>{rows.slice(-5).reverse().map(r=><tr key={r.checked_at}><td className="py-2 pr-4 whitespace-nowrap">{r.checked_at}</td><td className="pr-4">{r.metadata_json.verified?r.status:'Unverified'}</td><td className="pr-4">{r.latency_ms} ms</td><td>{r.message} · {r.metadata_json.scope}</td></tr>)}</tbody></table></div></section>;})}</main>;
}
