import React from 'react';
import { AlertTriangle, X, ExternalLink, Shield } from 'lucide-react';

interface LinkValidationModalProps {
    isOpen: boolean;
    onClose: () => void;
    link: string;
    warning: string;
}

export const LinkValidationModal: React.FC<LinkValidationModalProps> = ({
    isOpen,
    onClose,
    link,
    warning
}) => {
    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
            <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 max-w-md w-full">
                {/* Header */}
                <div className="flex items-center justify-between mb-6">
                    <h3 className="text-xl font-bold text-white">Link Validation Warning</h3>
                    <button
                        onClick={onClose}
                        className="p-1 hover:bg-slate-800 rounded transition-colors"
                    >
                        <X className="w-5 h-5 text-slate-400" />
                    </button>
                </div>

                {/* Warning Icon */}
                <div className="flex items-center justify-center mb-6">
                    <div className="w-16 h-16 rounded-full bg-yellow-500/10 flex items-center justify-center">
                        <AlertTriangle className="w-8 h-8 text-yellow-500" />
                    </div>
                </div>

                {/* Warning Message */}
                <div className="text-center mb-6">
                    <h4 className="text-lg font-bold text-white mb-2">
                        External Link Detected
                    </h4>
                    <p className="text-slate-400 text-sm">
                        {warning}
                    </p>
                </div>

                {/* Link Display */}
                <div className="bg-slate-800/50 border border-slate-700 rounded-lg p-4 mb-6">
                    <div className="flex items-start gap-3">
                        <ExternalLink className="w-5 h-5 text-slate-400 flex-shrink-0 mt-0.5" />
                        <div className="flex-1 min-w-0">
                            <p className="text-xs text-slate-500 mb-1">Blocked Link:</p>
                            <p className="text-sm text-slate-300 break-all">{link}</p>
                        </div>
                    </div>
                </div>

                {/* Security Notice */}
                <div className="bg-red-500/10 border border-red-500/20 rounded-lg p-4 mb-6">
                    <div className="flex items-start gap-3">
                        <Shield className="w-5 h-5 text-red-400 flex-shrink-0 mt-0.5" />
                        <div>
                            <p className="text-xs text-red-400">
                                <strong>Security Policy:</strong> Only links generated by AlphaClone Systems can be shared through our platform. This protects you and your clients from phishing and malicious links.
                            </p>
                        </div>
                    </div>
                </div>

                {/* Actions */}
                <div className="flex justify-end gap-3">
                    <button
                        onClick={onClose}
                        className="px-4 py-2 bg-slate-800 hover:bg-slate-700 rounded-lg transition-colors text-white font-medium"
                    >
                        I Understand
                    </button>
                </div>
            </div>
        </div>
    );
};
