import { NextRequest, NextResponse } from 'next/server';
import { requireTenantAccess, createAdminSupabaseClientOrThrow, routeErrorResponse } from '@/lib/apiAuth';
import jsPDF from 'jspdf';

export async function GET(
  req: NextRequest,
  context: { params: Promise<{ id: string }> }
) {
  try {
    const { id: invoiceId } = await context.params;
    const { searchParams } = new URL(req.url);
    const tenantId = searchParams.get('tenantId');

    if (!tenantId) {
      return NextResponse.json({ error: 'tenantId query param required' }, { status: 400 });
    }

    await requireTenantAccess(tenantId);
    const admin = createAdminSupabaseClientOrThrow();

    // Fetch invoice
    const { data: invoice, error: invErr } = await admin
      .from('business_invoices')
      .select('id, invoice_number, status, sent_at, viewed_at, delivery_status, tenant_id, view_count')
      .eq('id', invoiceId)
      .eq('tenant_id', tenantId)
      .single();

    if (invErr || !invoice) {
      return NextResponse.json({ error: 'Invoice not found' }, { status: 404 });
    }

    // Fetch delivery log
    const { data: deliveryLog } = await admin
      .from('invoice_delivery_log')
      .select('sent_at, delivered_at, opened_at, bounced_at, sent_to_email, email_provider, delivery_status')
      .eq('invoice_id', invoiceId)
      .order('sent_at', { ascending: false })
      .limit(1)
      .maybeSingle();

    // Generate PDF certificate
    const doc = new jsPDF({ orientation: 'p', unit: 'mm', format: 'a4' });
    const margin = 20;
    const pageWidth = doc.internal.pageSize.width;

    // Header
    doc.setFillColor('#0f172a');
    doc.rect(0, 0, pageWidth, 40, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.setTextColor('#ffffff');
    doc.text('INVOICE DELIVERY CERTIFICATE', margin, 22);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor('#94a3b8');
    doc.text('Official E-Delivery Proof Document', margin, 30);

    let y = 55;

    // Certificate body
    const addRow = (label: string, value: string, color?: string) => {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor('#64748b');
      doc.text(label.toUpperCase(), margin, y);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(11);
      doc.setTextColor(color || '#0f172a');
      doc.text(value || '—', margin, y + 6);
      y += 18;
    };

    const formatTs = (ts?: string | null) =>
      ts ? new Date(ts).toLocaleString('en-GB', { timeZone: 'UTC' }) + ' UTC' : '—';

    addRow('Invoice Number', invoice.invoice_number);
    addRow('Invoice ID', invoice.id);
    addRow('Sent To', deliveryLog?.sent_to_email || '—');
    addRow('Sent At', formatTs(deliveryLog?.sent_at || invoice.sent_at));
    addRow('Email Provider', deliveryLog?.email_provider || '—');

    y += 4;
    doc.setDrawColor('#e2e8f0');
    doc.line(margin, y, pageWidth - margin, y);
    y += 12;

    const statusColor: Record<string, string> = {
      DELIVERED: '#10b981',
      BOUNCED: '#ef4444',
      OPENED: '#0ea5e9',
      PENDING: '#f59e0b',
    };

    addRow(
      'Delivery Status',
      deliveryLog?.delivery_status || invoice.delivery_status,
      statusColor[deliveryLog?.delivery_status || invoice.delivery_status] || '#0f172a'
    );
    addRow('Delivered At', formatTs(deliveryLog?.delivered_at));
    addRow('Opened At (Email)', formatTs(deliveryLog?.opened_at));
    addRow('First Viewed (Web Portal)', formatTs(invoice.viewed_at));
    addRow('Total View Count', String(invoice.view_count ?? 0));

    y += 4;
    doc.setDrawColor('#e2e8f0');
    doc.line(margin, y, pageWidth - margin, y);
    y += 16;

    // Certificate note
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9);
    doc.setTextColor('#64748b');
    const note = doc.splitTextToSize(
      'This certificate was automatically generated by AlphaClone Systems and constitutes legal evidence of invoice delivery. All timestamps are recorded in Coordinated Universal Time (UTC). This document may be used in dispute resolution proceedings.',
      pageWidth - margin * 2
    );
    doc.text(note, margin, y);

    y += note.length * 5 + 16;

    // Seal
    doc.setFillColor('#f0fdf4');
    doc.setDrawColor('#10b981');
    doc.roundedRect(margin, y, pageWidth - margin * 2, 20, 3, 3, 'FD');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor('#166534');
    doc.text(
      `Generated: ${new Date().toLocaleString('en-GB', { timeZone: 'UTC' })} UTC`,
      margin + 6,
      y + 13
    );

    const pdfBytes = doc.output('arraybuffer');
    const filename = `Delivery_Certificate_${invoice.invoice_number}.pdf`;

    return new NextResponse(Buffer.from(pdfBytes), {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Cache-Control': 'no-store',
      },
    });
  } catch (err) {
    return routeErrorResponse(err, 'Failed to generate delivery certificate', req);
  }
}
