import type { Metadata } from 'next';
import { LegalPageShell } from '@/components/legal/LegalPageShell';

export const metadata: Metadata = {
  title: 'Acceptable Use Policy | AlphaClone Systems',
  description: 'Acceptable use policy for AlphaClone Systems LLC.',
  alternates: { canonical: 'https://alphaclonesystems.com/legal/acceptable-use' },
  robots: { index: true, follow: true },
};

export default function Page() {
  return (
    <LegalPageShell
      title="Acceptable Use Policy"
      lastUpdated="June 9, 2025"
      intro="This policy sets out the acceptable and prohibited uses of AlphaClone Systems LLC services."
      sections={[
        { id: 'purpose', title: 'Purpose' },
        { id: 'permitted', title: 'Permitted uses' },
        { id: 'prohibited', title: 'Prohibited uses' },
        { id: 'ai', title: 'AI-specific rules' },
        { id: 'integrations', title: 'Social and messaging integrations' },
        { id: 'enforcement', title: 'Enforcement' },
        { id: 'reporting', title: 'Reporting' },
      ]}
      badge="Use"
    >
      <section id="purpose" className="scroll-mt-28 space-y-3">
        <h2 className="text-xl font-semibold text-white">Purpose</h2>
        <p className="text-sm leading-7 text-slate-300">We want the platform to stay useful, lawful, and respectful for everyone using it.</p>
      </section>
      <section id="permitted" className="scroll-mt-28 space-y-3">
        <h2 className="text-xl font-semibold text-white">Permitted uses</h2>
        <p className="text-sm leading-7 text-slate-300">You may use the platform for legitimate business operations across your CRM, invoicing, contracts, projects, and automation workflows.</p>
      </section>
      <section id="prohibited" className="scroll-mt-28 space-y-3">
        <h2 className="text-xl font-semibold text-white">Prohibited uses</h2>
        <ul className="space-y-2 text-sm leading-7 text-slate-300">
          <li>Sending spam or unsolicited bulk email through our infrastructure.</li>
          <li>Using Bonnie AI to generate illegal, harmful, or deceptive content.</li>
          <li>Scraping or bulk-exporting data to compete with AlphaClone.</li>
          <li>Sharing account credentials or attempting to reverse-engineer the platform.</li>
          <li>Using the platform to violate any applicable law or rate-limit policy.</li>
          <li>Abusing API or MCP tools.</li>
        </ul>
      </section>
      <section id="ai" className="scroll-mt-28 space-y-3">
        <h2 className="text-xl font-semibold text-white">AI-specific rules</h2>
        <p className="text-sm leading-7 text-slate-300">Always review Bonnie AI output before sending it to clients or publishing it elsewhere. You are responsible for content generated by your account.</p>
      </section>
      <section id="integrations" className="scroll-mt-28 space-y-3">
        <h2 className="text-xl font-semibold text-white">Social and messaging integrations</h2>
        <p className="text-sm leading-7 text-slate-300">When using Meta, LinkedIn, Google, or Twilio integrations, you must also comply with those providers’ acceptable use rules.</p>
      </section>
      <section id="enforcement" className="scroll-mt-28 space-y-3">
        <h2 className="text-xl font-semibold text-white">Enforcement</h2>
        <p className="text-sm leading-7 text-slate-300">Violations may result in immediate account suspension without refund.</p>
      </section>
      <section id="reporting" className="scroll-mt-28 space-y-3">
        <h2 className="text-xl font-semibold text-white">Reporting</h2>
        <p className="text-sm leading-7 text-slate-300">Report concerns to legal@alphaclonesystems.com.</p>
      </section>
    </LegalPageShell>
  );
}
