'use client';
import { useEffect, useState } from 'react';
import { Download, FileText, Loader2, ShieldCheck } from 'lucide-react';
import { useParams } from 'next/navigation';

export default function PublicDataRoomPage() {
  const params = useParams<{ token: string }>();
  const [data, setData] = useState<any>(null); const [error,setError]=useState('');
  useEffect(()=>{ if(!params?.token)return; void fetch(`/api/public/document-data-rooms/${encodeURIComponent(params.token)}`).then(async response=>{const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Data room unavailable');setData(payload.dataRoom);}).catch(reason=>setError(reason instanceof Error?reason.message:'Data room unavailable')); },[params?.token]);
  return <main className="min-h-dvh bg-slate-950 px-4 py-10 text-slate-100"><div className="mx-auto max-w-5xl"><div className="mb-8 flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-teal-500/10 text-teal-300"><ShieldCheck className="h-5 w-5" /></span><div><p className="text-xs font-black uppercase tracking-[.2em] text-teal-300">Secure data room</p><h1 className="text-xl font-semibold">{data?.name||'Loading shared documents…'}</h1></div></div>{error?<div className="rounded-2xl border border-rose-500/20 bg-rose-500/5 p-8 text-center text-sm text-rose-200">{error}</div>:!data?<div className="flex min-h-60 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-teal-300" /></div>:<><p className="mb-4 text-xs text-slate-500">Access expires {data.expiresAt?new Date(data.expiresAt).toLocaleString():'when the owner revokes this link'}.</p><div className="grid gap-3">{data.items.map((item:any)=><article key={item.id} className="rounded-2xl border border-white/10 bg-slate-900/60 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex min-w-0 items-start gap-3"><FileText className="mt-0.5 h-5 w-5 shrink-0 text-teal-300"/><div><h2 className="font-semibold text-white">{item.document.name}</h2><p className="text-xs text-slate-500">{item.document.mimeType||'Document'} · {item.document.sizeBytes?`${Math.round(item.document.sizeBytes/1024)} KB`:''}</p>{item.document.summary?<p className="mt-2 text-sm leading-6 text-slate-400">{item.document.summary}</p>:null}</div></div>{item.document.previewUrl?<a href={item.document.previewUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-teal-600 px-3 py-2 text-xs font-bold text-white">{item.allowDownload?<Download className="h-4 w-4"/>:<FileText className="h-4 w-4"/>}{item.allowDownload?'Open / download':'View securely'}</a>:null}</div></article>)}</div></>}</div></main>;
}
