/**
 * Link Validator - Ensures only system-generated links are shared
 * 
 * SECURITY POLICY: Only links generated by AlphaClone Systems can be shared.
 * External links (Zoom, Google Meet, Daily.co, etc.) are blocked to prevent:
 * - Phishing attacks
 * - Domain exposure (users should NEVER see alphaclone.daily.co)
 * - External platform dependency visibility
 */

const ALLOWED_DOMAINS = [
    'localhost',
    '127.0.0.1',
    'alphaclone.vercel.app',
    'alphaclone.com',
    'www.alphaclone.com',
    // Add your production domains here
];

const ALLOWED_PATHS = [
    '/call/',
    '/book/',
    '/meeting/',
    '/dashboard',
];

// REMOVED: Daily.co from trusted external domains
// Daily.co URLs should NEVER be exposed to users
// All video calls must use system routes: /call/[id]

export interface LinkValidationResult {
    isValid: boolean;
    isSystemLink: boolean;
    isTrustedExternal: boolean;
    reason?: string;
    warning?: string;
}

export const linkValidator = {
    /**
     * Validate if a link can be shared
     * CRITICAL: Daily.co links are now BLOCKED from sharing
     */
    validateLink(url: string): LinkValidationResult {
        try {
            const parsedUrl = new URL(url);

            // REMOVED: Daily.co trusted external check
            // Daily.co URLs must never be shared or exposed

            // Check if it's a Daily.co URL (now BLOCKED)
            if (parsedUrl.hostname.includes('daily.co')) {
                return {
                    isValid: false,
                    isSystemLink: false,
                    isTrustedExternal: false,
                    reason: 'Daily.co domain exposure prevented',
                    warning: 'Video meeting links cannot be shared directly. Please use the system-generated meeting link from your dashboard instead.'
                };
            }

            // Check if domain is our system
            const isDomainAllowed = ALLOWED_DOMAINS.some(domain =>
                parsedUrl.hostname === domain || parsedUrl.hostname.includes(domain)
            );

            if (!isDomainAllowed) {
                return {
                    isValid: false,
                    isSystemLink: false,
                    isTrustedExternal: false,
                    reason: 'External domain not allowed',
                    warning: 'This link is not generated by our system and cannot be shared for security reasons. Only AlphaClone-generated links are allowed.'
                };
            }

            // Check if path is allowed for sharing
            const isPathAllowed = ALLOWED_PATHS.some(path =>
                parsedUrl.pathname.startsWith(path)
            );

            if (!isPathAllowed) {
                return {
                    isValid: false,
                    isSystemLink: true,
                    isTrustedExternal: false,
                    reason: 'Path not allowed for sharing',
                    warning: 'This system link cannot be shared externally. Only meeting and booking links can be shared.'
                };
            }

            return {
                isValid: true,
                isSystemLink: true,
                isTrustedExternal: false
            };

        } catch (error) {
            return {
                isValid: false,
                isSystemLink: false,
                isTrustedExternal: false,
                reason: 'Invalid URL format',
                warning: 'The provided link is not a valid URL.'
            };
        }
    },

    /**
     * Check if link is from Daily.co
     * DEPRECATED: Daily.co links should never be exposed
     */
    isDailyLink(url: string): boolean {
        try {
            const parsedUrl = new URL(url);
            return parsedUrl.hostname.includes('daily.co');
        } catch {
            return false;
        }
    },

    /**
     * Generate system meeting link
     * This is the ONLY type of video link users should see
     */
    generateMeetingLink(callId: string): string {
        const baseUrl = typeof window !== 'undefined'
            ? window.location.origin
            : process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000';

        return `${baseUrl}/call/${callId}`;
    },

    /**
     * Extract URLs from text
     */
    extractUrls(text: string): string[] {
        const urlRegex = /(https?:\/\/[^\s]+)/g;
        return text.match(urlRegex) || [];
    },

    /**
     * Validate all URLs in text
     */
    validateTextUrls(text: string): { allValid: boolean; invalidUrls: string[]; warnings: string[] } {
        const urls = this.extractUrls(text);
        const invalidUrls: string[] = [];
        const warnings: string[] = [];

        for (const url of urls) {
            const validation = this.validateLink(url);
            if (!validation.isValid) {
                invalidUrls.push(url);
                if (validation.warning) {
                    warnings.push(validation.warning);
                }
            }
        }

        return {
            allValid: invalidUrls.length === 0,
            invalidUrls,
            warnings
        };
    }
};
