/**
 * Link Validator - Ensures only system-generated links are shared
 * 
 * SECURITY POLICY: Only links generated by AlphaClone Systems can be shared.
 * External links (Zoom, Google Meet, etc.) are blocked to prevent phishing.
 */

const ALLOWED_DOMAINS = [
    'localhost',
    '127.0.0.1',
    'alphaclone.vercel.app',
    'alphaclone.com',
    'www.alphaclone.com',
    // Add your production domains here
];

const ALLOWED_PATHS = [
    '/call/',
    '/book/',
    '/meeting/',
    '/dashboard',
];

// Daily.co is our video provider, so we allow it
const TRUSTED_EXTERNAL_DOMAINS = [
    'daily.co',
    'dashboard.daily.co',
];

export interface LinkValidationResult {
    isValid: boolean;
    isSystemLink: boolean;
    isTrustedExternal: boolean;
    reason?: string;
    warning?: string;
}

export const linkValidator = {
    /**
     * Validate if a link can be shared
     */
    validateLink(url: string): LinkValidationResult {
        try {
            const parsedUrl = new URL(url);

            // Check if it's a trusted external domain (Daily.co)
            const isTrustedExternal = TRUSTED_EXTERNAL_DOMAINS.some(domain =>
                parsedUrl.hostname.includes(domain)
            );

            if (isTrustedExternal) {
                return {
                    isValid: true,
                    isSystemLink: false,
                    isTrustedExternal: true
                };
            }

            // Check if domain is our system
            const isDomainAllowed = ALLOWED_DOMAINS.some(domain =>
                parsedUrl.hostname === domain || parsedUrl.hostname.includes(domain)
            );

            if (!isDomainAllowed) {
                return {
                    isValid: false,
                    isSystemLink: false,
                    isTrustedExternal: false,
                    reason: 'External domain not allowed',
                    warning: 'This link is not generated by our system and cannot be shared for security reasons. Only AlphaClone-generated links and Daily.co video links are allowed.'
                };
            }

            // Check if path is allowed for sharing
            const isPathAllowed = ALLOWED_PATHS.some(path =>
                parsedUrl.pathname.startsWith(path)
            );

            if (!isPathAllowed) {
                return {
                    isValid: false,
                    isSystemLink: true,
                    isTrustedExternal: false,
                    reason: 'Path not allowed for sharing',
                    warning: 'This system link cannot be shared externally. Only meeting and booking links can be shared.'
                };
            }

            return {
                isValid: true,
                isSystemLink: true,
                isTrustedExternal: false
            };

        } catch (error) {
            return {
                isValid: false,
                isSystemLink: false,
                isTrustedExternal: false,
                reason: 'Invalid URL format',
                warning: 'The provided link is not a valid URL.'
            };
        }
    },

    /**
     * Check if link is from Daily.co (our video provider)
     */
    isDailyLink(url: string): boolean {
        try {
            const parsedUrl = new URL(url);
            return TRUSTED_EXTERNAL_DOMAINS.some(domain =>
                parsedUrl.hostname.includes(domain)
            );
        } catch {
            return false;
        }
    },

    /**
     * Generate system meeting link
     */
    generateMeetingLink(callId: string): string {
        const baseUrl = typeof window !== 'undefined'
            ? window.location.origin
            : process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000';

        return `${baseUrl}/call/${callId}`;
    },

    /**
     * Extract URLs from text
     */
    extractUrls(text: string): string[] {
        const urlRegex = /(https?:\/\/[^\s]+)/g;
        return text.match(urlRegex) || [];
    },

    /**
     * Validate all URLs in text
     */
    validateTextUrls(text: string): { allValid: boolean; invalidUrls: string[]; warnings: string[] } {
        const urls = this.extractUrls(text);
        const invalidUrls: string[] = [];
        const warnings: string[] = [];

        for (const url of urls) {
            const validation = this.validateLink(url);
            if (!validation.isValid) {
                invalidUrls.push(url);
                if (validation.warning) {
                    warnings.push(validation.warning);
                }
            }
        }

        return {
            allValid: invalidUrls.length === 0,
            invalidUrls,
            warnings
        };
    }
};
