import type {
  EmailCommunicationClass,
  EmailDeliveryPriority,
  EmailLayoutFamily,
  EmailPurposeFamily,
  UnsubscribePolicy,
} from '@/lib/email/emailCommunicationClasses';

export interface EmailPurposeDefinition {
  templateKey: string;
  family: EmailPurposeFamily;
  communicationClass: EmailCommunicationClass;
  layoutFamily: EmailLayoutFamily;
  /** Preference category key for category-specific unsubscribe */
  preferenceCategory: string;
  defaultPriority: EmailDeliveryPriority;
  unsubscribePolicy: UnsubscribePolicy;
  subjectTemplate: string;
  preheaderTemplate: string;
  headlineTemplate: string;
  bodyTemplate: string;
  ctaLabel?: string;
  variants?: string[];
  /** Backend event type that triggers this email, when wired */
  eventType?: string;
  /** Whether a backend trigger is currently connected */
  wired: boolean;
}

type PurposeSeed = Omit<EmailPurposeDefinition, 'templateKey'> & { key: string };

function definePurposes(seeds: PurposeSeed[]): Record<string, EmailPurposeDefinition> {
  const registry: Record<string, EmailPurposeDefinition> = {};
  for (const seed of seeds) {
    const { key, ...rest } = seed;
    registry[key] = { templateKey: key, ...rest };
  }
  return registry;
}

const ACCOUNT_AUTH: PurposeSeed[] = [
  { key: 'verify_email', family: 'account_auth', communicationClass: 'transactional', layoutFamily: 'security', preferenceCategory: 'account_security', defaultPriority: 'critical', unsubscribePolicy: 'none', subjectTemplate: 'Verify your AlphaClone email', preheaderTemplate: 'Confirm your address to secure your workspace.', headlineTemplate: 'Verify your email', bodyTemplate: '<p>Please confirm your email address to activate your AlphaClone workspace.</p>', ctaLabel: 'Verify Email', wired: true, eventType: 'auth.verify_email' },
  { key: 'verification_reminder', family: 'account_auth', communicationClass: 'transactional', layoutFamily: 'security', preferenceCategory: 'account_security', defaultPriority: 'high', unsubscribePolicy: 'none', subjectTemplate: 'Reminder: verify your email', preheaderTemplate: 'Your workspace is waiting — one quick step left.', headlineTemplate: 'Verification reminder', bodyTemplate: '<p>Your account setup is almost complete. Verify your email to unlock the full workspace.</p>', ctaLabel: 'Verify Now', wired: false },
  { key: 'verification_successful', family: 'account_auth', communicationClass: 'transactional', layoutFamily: 'success', preferenceCategory: 'account_security', defaultPriority: 'normal', unsubscribePolicy: 'none', subjectTemplate: 'Email verified — welcome aboard', preheaderTemplate: 'Your AlphaClone workspace is ready.', headlineTemplate: 'Email verified', bodyTemplate: '<p>Your email is confirmed. You can now access all workspace features.</p>', ctaLabel: 'Open Workspace', wired: false },
  { key: 'welcome', family: 'account_auth', communicationClass: 'transactional', layoutFamily: 'welcome', preferenceCategory: 'account_security', defaultPriority: 'high', unsubscribePolicy: 'none', subjectTemplate: 'Welcome to AlphaClone Systems', preheaderTemplate: 'CRM · Leads · Outreach · Invoices · Automation — all connected.', headlineTemplate: 'Welcome to AlphaClone Systems', bodyTemplate: '<p>Your business systems are now connected in one workspace.</p><p><strong>CRM · Leads · Sales · Outreach · Email · Calendar · Documents · Contracts · Invoices · Social · Reporting · Automation</strong></p><p>We\'ll keep you informed when something important happens — new leads, replies, meetings, invoices, and campaign results.</p>', ctaLabel: 'Open Your Workspace', wired: true, eventType: 'auth.welcome' },
  { key: 'complete_account_setup', family: 'account_auth', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'account_security', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: 'Complete your account setup', preheaderTemplate: 'A few steps remain before your workspace is fully active.', headlineTemplate: 'Complete your setup', bodyTemplate: '<p>Finish setting up your profile and workspace preferences to get the most from AlphaClone.</p>', ctaLabel: 'Continue Setup', wired: false },
  { key: 'password_reset', family: 'account_auth', communicationClass: 'transactional', layoutFamily: 'security', preferenceCategory: 'account_security', defaultPriority: 'critical', unsubscribePolicy: 'none', subjectTemplate: 'Reset your AlphaClone password', preheaderTemplate: 'This link expires soon. If you did not request this, ignore this email.', headlineTemplate: 'Password reset', bodyTemplate: '<p>We received a request to reset your password. Use the button below to choose a new one.</p>', ctaLabel: 'Reset Password', wired: true, eventType: 'auth.password_reset' },
  { key: 'password_changed', family: 'account_auth', communicationClass: 'transactional', layoutFamily: 'security', preferenceCategory: 'account_security', defaultPriority: 'critical', unsubscribePolicy: 'none', subjectTemplate: 'Your password was changed', preheaderTemplate: 'If this wasn\'t you, secure your account immediately.', headlineTemplate: 'Password changed', bodyTemplate: '<p>Your AlphaClone password was updated successfully.</p>', wired: false },
  { key: 'email_address_changed', family: 'account_auth', communicationClass: 'transactional', layoutFamily: 'security', preferenceCategory: 'account_security', defaultPriority: 'critical', unsubscribePolicy: 'none', subjectTemplate: 'Your email address was updated', preheaderTemplate: 'Confirm this change if you did not initiate it.', headlineTemplate: 'Email address changed', bodyTemplate: '<p>The email address on your account was changed.</p>', wired: false },
  { key: 'new_login_detected', family: 'account_auth', communicationClass: 'transactional', layoutFamily: 'security', preferenceCategory: 'account_security', defaultPriority: 'critical', unsubscribePolicy: 'none', subjectTemplate: 'New login to your AlphaClone account', preheaderTemplate: 'Review this sign-in if you don\'t recognise it.', headlineTemplate: 'New login detected', bodyTemplate: '<p>A new sign-in to your account was detected.</p>', wired: false },
  { key: 'account_security_alert', family: 'account_auth', communicationClass: 'transactional', layoutFamily: 'security', preferenceCategory: 'account_security', defaultPriority: 'critical', unsubscribePolicy: 'none', subjectTemplate: 'Security alert on your account', preheaderTemplate: 'Immediate review recommended.', headlineTemplate: 'Account security alert', bodyTemplate: '<p>We detected unusual activity on your account that requires your attention.</p>', ctaLabel: 'Review Security', wired: false },
];

const ONBOARDING: PurposeSeed[] = [
  { key: 'complete_business_profile', family: 'onboarding', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'onboarding', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: 'Complete your business profile', preheaderTemplate: 'Help AlphaClone personalise your workspace.', headlineTemplate: 'Complete your business profile', bodyTemplate: '<p>Add your business details so AlphaClone can tailor outreach, invoices, and reporting.</p>', ctaLabel: 'Complete Profile', wired: false },
  { key: 'connect_first_integration', family: 'onboarding', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'onboarding', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: 'Connect your first integration', preheaderTemplate: 'Link the tools you already use.', headlineTemplate: 'Connect an integration', bodyTemplate: '<p>Connect email, calendar, or social accounts to unlock automation.</p>', ctaLabel: 'Connect Integration', wired: false },
  { key: 'import_first_contacts', family: 'onboarding', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'onboarding', defaultPriority: 'low', unsubscribePolicy: 'category', subjectTemplate: 'Import your first contacts', preheaderTemplate: 'Bring your CRM data into AlphaClone.', headlineTemplate: 'Import contacts', bodyTemplate: '<p>Upload or sync contacts to start managing relationships in one place.</p>', ctaLabel: 'Import Contacts', wired: false },
  { key: 'add_first_lead', family: 'onboarding', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'onboarding', defaultPriority: 'low', unsubscribePolicy: 'category', subjectTemplate: 'Add your first lead', preheaderTemplate: 'Start building your pipeline today.', headlineTemplate: 'Add your first lead', bodyTemplate: '<p>Create or import a lead to begin tracking opportunities.</p>', ctaLabel: 'Add Lead', wired: false },
  { key: 'create_first_campaign', family: 'onboarding', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'onboarding', defaultPriority: 'low', unsubscribePolicy: 'category', subjectTemplate: 'Create your first campaign', preheaderTemplate: 'Reach prospects with structured outreach.', headlineTemplate: 'Create a campaign', bodyTemplate: '<p>Set up your first outreach campaign and let AlphaClone handle delivery.</p>', ctaLabel: 'Create Campaign', wired: false },
  { key: 'send_first_outreach', family: 'onboarding', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'onboarding', defaultPriority: 'low', unsubscribePolicy: 'category', subjectTemplate: 'Send your first outreach', preheaderTemplate: 'Your pipeline is ready — start the conversation.', headlineTemplate: 'Send first outreach', bodyTemplate: '<p>Review recipients and launch your first outreach sequence.</p>', ctaLabel: 'Start Outreach', wired: false },
  { key: 'create_first_invoice', family: 'onboarding', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'onboarding', defaultPriority: 'low', unsubscribePolicy: 'category', subjectTemplate: 'Create your first invoice', preheaderTemplate: 'Bill clients directly from AlphaClone.', headlineTemplate: 'Create an invoice', bodyTemplate: '<p>Generate and send professional invoices in minutes.</p>', ctaLabel: 'Create Invoice', wired: false },
  { key: 'connect_calendar', family: 'onboarding', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'onboarding', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: 'Connect your calendar', preheaderTemplate: 'Sync meetings and booking links.', headlineTemplate: 'Connect calendar', bodyTemplate: '<p>Link your calendar so meetings and reminders stay in sync.</p>', ctaLabel: 'Connect Calendar', wired: false },
  { key: 'complete_workspace_setup', family: 'onboarding', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'onboarding', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: 'Finish setting up your workspace', preheaderTemplate: '{{lead_count}} steps remain.', headlineTemplate: 'Complete workspace setup', bodyTemplate: '<p>Finish the remaining setup steps to unlock the full AlphaClone experience.</p>', ctaLabel: 'Continue Setup', wired: false },
  { key: 'first_week_onboarding_summary', family: 'onboarding', communicationClass: 'digest', layoutFamily: 'morning_brief', preferenceCategory: 'onboarding', defaultPriority: 'low', unsubscribePolicy: 'category', subjectTemplate: 'Your first week with AlphaClone', preheaderTemplate: 'See what you\'ve accomplished so far.', headlineTemplate: 'First-week summary', bodyTemplate: '<p>Here\'s a snapshot of your first week — leads added, outreach sent, and integrations connected.</p>', ctaLabel: 'View Dashboard', wired: false },
];

const BUSINESS_INTELLIGENCE: PurposeSeed[] = [
  { key: 'morning_business_brief', family: 'business_intelligence', communicationClass: 'digest', layoutFamily: 'morning_brief', preferenceCategory: 'reports_morning_brief', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: 'Your morning business brief is ready', preheaderTemplate: '{{lead_count}} updates while you were away.', headlineTemplate: '{{greeting}}', bodyTemplate: '<p><strong>While you were away</strong></p><p>{{lead_count}} leads · {{reply_count}} replies</p><p><strong>Needs your attention</strong></p><p>Review today\'s priorities in your workspace.</p>', ctaLabel: 'Open Today\'s Workspace', wired: true, eventType: 'digest.morning_brief' },
  { key: 'end_of_day_summary', family: 'business_intelligence', communicationClass: 'digest', layoutFamily: 'morning_brief', preferenceCategory: 'reports_eod', defaultPriority: 'low', unsubscribePolicy: 'category', subjectTemplate: 'Your end-of-day summary', preheaderTemplate: 'Today\'s results at a glance.', headlineTemplate: 'End-of-day summary', bodyTemplate: '<p>Here\'s what happened in your business today.</p>', ctaLabel: 'View Summary', wired: false },
  { key: 'weekly_business_review', family: 'business_intelligence', communicationClass: 'digest', layoutFamily: 'morning_brief', preferenceCategory: 'reports_weekly', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: 'Your weekly business review', preheaderTemplate: 'Performance across CRM, outreach, and revenue.', headlineTemplate: 'Weekly business review', bodyTemplate: '<p>Your weekly performance summary is ready.</p>', ctaLabel: 'View Report', wired: false },
  { key: 'monthly_business_review', family: 'business_intelligence', communicationClass: 'digest', layoutFamily: 'morning_brief', preferenceCategory: 'reports_monthly', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: 'Your monthly business review', preheaderTemplate: 'Full month performance snapshot.', headlineTemplate: 'Monthly business review', bodyTemplate: '<p>Your monthly performance report is ready.</p>', ctaLabel: 'View Report', wired: false },
  { key: 'sales_summary', family: 'business_intelligence', communicationClass: 'digest', layoutFamily: 'morning_brief', preferenceCategory: 'reports_sales', defaultPriority: 'low', unsubscribePolicy: 'category', subjectTemplate: 'Sales summary for {{business_name}}', preheaderTemplate: 'Pipeline and deal activity update.', headlineTemplate: 'Sales summary', bodyTemplate: '<p>Latest sales pipeline and deal activity.</p>', wired: false },
  { key: 'crm_summary', family: 'business_intelligence', communicationClass: 'digest', layoutFamily: 'morning_brief', preferenceCategory: 'reports_crm', defaultPriority: 'low', unsubscribePolicy: 'category', subjectTemplate: 'CRM summary — {{lead_count}} leads need attention', preheaderTemplate: 'Lead and contact activity update.', headlineTemplate: 'CRM summary', bodyTemplate: '<p>Recent CRM activity and follow-ups due.</p>', wired: false },
  { key: 'outreach_summary', family: 'business_intelligence', communicationClass: 'digest', layoutFamily: 'morning_brief', preferenceCategory: 'reports_outreach', defaultPriority: 'low', unsubscribePolicy: 'category', subjectTemplate: 'Outreach summary — {{reply_count}} replies', preheaderTemplate: 'Campaign performance at a glance.', headlineTemplate: 'Outreach summary', bodyTemplate: '<p>Campaign sends, opens, and replies this period.</p>', wired: false },
  { key: 'revenue_summary', family: 'business_intelligence', communicationClass: 'digest', layoutFamily: 'morning_brief', preferenceCategory: 'reports_finance', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: 'Revenue summary for {{business_name}}', preheaderTemplate: 'Invoices, payments, and outstanding balances.', headlineTemplate: 'Revenue summary', bodyTemplate: '<p>Financial activity and outstanding invoices.</p>', wired: false },
  { key: 'marketing_performance_summary', family: 'business_intelligence', communicationClass: 'digest', layoutFamily: 'morning_brief', preferenceCategory: 'reports_marketing', defaultPriority: 'low', unsubscribePolicy: 'category', subjectTemplate: 'Marketing performance update', preheaderTemplate: 'Social and campaign metrics.', headlineTemplate: 'Marketing performance', bodyTemplate: '<p>Social posts, campaigns, and engagement metrics.</p>', wired: false },
  { key: 'upcoming_work_summary', family: 'business_intelligence', communicationClass: 'digest', layoutFamily: 'morning_brief', preferenceCategory: 'reports_upcoming', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: 'Upcoming work for the week', preheaderTemplate: 'Meetings, deadlines, and follow-ups.', headlineTemplate: 'Upcoming work', bodyTemplate: '<p>Your schedule and priorities for the coming days.</p>', ctaLabel: 'View Calendar', wired: false },
];

const CRM_LEADS: PurposeSeed[] = [
  { key: 'new_lead_created', family: 'crm_leads', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'crm_leads', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: 'New lead: {{lead_name}}', preheaderTemplate: 'Added to your CRM pipeline.', headlineTemplate: 'New lead created', bodyTemplate: '<p><strong>{{lead_name}}</strong> was added to your CRM.</p>', ctaLabel: 'View Lead', wired: true, eventType: 'lead.created' },
  { key: 'bulk_leads_imported', family: 'crm_leads', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'crm_leads', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: '{{lead_count}} leads imported to your CRM', preheaderTemplate: 'Import completed with deduplication applied.', headlineTemplate: 'Bulk leads imported', bodyTemplate: '<p><strong>{{lead_count}}</strong> leads were imported to your CRM.</p>', ctaLabel: 'View Leads', wired: true, eventType: 'lead.imported_bulk' },
  { key: 'lead_qualified', family: 'crm_leads', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'crm_leads', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: '{{lead_name}} was qualified', preheaderTemplate: 'Ready for outreach or assignment.', headlineTemplate: 'Lead qualified', bodyTemplate: '<p><strong>{{lead_name}}</strong> meets your qualification criteria.</p>', ctaLabel: 'View Lead', wired: false },
  { key: 'lead_score_increased', family: 'crm_leads', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'crm_leads', defaultPriority: 'low', unsubscribePolicy: 'category', subjectTemplate: '{{lead_name}} score increased', preheaderTemplate: 'Engagement or fit signals detected.', headlineTemplate: 'Lead score increased', bodyTemplate: '<p><strong>{{lead_name}}</strong> score has increased based on recent activity.</p>', wired: false },
  { key: 'lead_replied', family: 'crm_leads', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'crm_leads', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: '{{lead_name}} replied to your outreach', preheaderTemplate: 'A prospect responded — review and follow up.', headlineTemplate: 'Lead replied', bodyTemplate: '<p><strong>{{lead_name}}</strong> replied to your outreach campaign.</p>', ctaLabel: 'View Reply', wired: false, eventType: 'lead.replied' },
  { key: 'lead_requires_follow_up', family: 'crm_leads', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'crm_leads', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: '{{lead_count}} leads need follow-up', preheaderTemplate: 'Scheduled follow-ups are due.', headlineTemplate: 'Follow-up required', bodyTemplate: '<p><strong>{{lead_count}}</strong> leads are waiting for your follow-up.</p>', ctaLabel: 'Review Leads', wired: false },
  { key: 'lead_became_opportunity', family: 'crm_leads', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'crm_sales', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: '{{lead_name}} became an opportunity', preheaderTemplate: 'Deal value: {{deal_value}}.', headlineTemplate: 'New opportunity', bodyTemplate: '<p><strong>{{lead_name}}</strong> moved to opportunity stage.</p>', ctaLabel: 'View Deal', wired: false },
  { key: 'opportunity_stage_changed', family: 'crm_leads', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'crm_sales', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: 'Deal stage updated — {{client_name}}', preheaderTemplate: 'Pipeline movement detected.', headlineTemplate: 'Opportunity stage changed', bodyTemplate: '<p>The deal for <strong>{{client_name}}</strong> moved to a new stage.</p>', wired: false },
  { key: 'deal_won', family: 'crm_leads', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'crm_sales', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: 'Deal won — {{client_name}}', preheaderTemplate: 'Value: {{deal_value}}.', headlineTemplate: 'Deal won', bodyTemplate: '<p>Congratulations — you won the deal with <strong>{{client_name}}</strong>.</p>', ctaLabel: 'View Deal', wired: false },
  { key: 'deal_lost', family: 'crm_leads', communicationClass: 'business_notification', layoutFamily: 'failure', preferenceCategory: 'crm_sales', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: 'Deal lost — {{client_name}}', preheaderTemplate: 'Review notes and next steps.', headlineTemplate: 'Deal lost', bodyTemplate: '<p>The deal with <strong>{{client_name}}</strong> was marked as lost.</p>', wired: false },
];

const OUTREACH_CAMPAIGNS: PurposeSeed[] = [
  { key: 'campaign_created', family: 'outreach_campaigns', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'outreach', defaultPriority: 'low', unsubscribePolicy: 'category', subjectTemplate: 'Campaign created: {{campaign_name}}', preheaderTemplate: 'Review and schedule when ready.', headlineTemplate: 'Campaign created', bodyTemplate: '<p>Your campaign <strong>{{campaign_name}}</strong> was created.</p>', wired: false },
  { key: 'campaign_scheduled', family: 'outreach_campaigns', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'outreach', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: '{{campaign_name}} is scheduled', preheaderTemplate: 'Delivery will begin automatically.', headlineTemplate: 'Campaign scheduled', bodyTemplate: '<p><strong>{{campaign_name}}</strong> is scheduled and will send automatically.</p>', wired: false },
  { key: 'campaign_started', family: 'outreach_campaigns', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'outreach', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: '{{campaign_name}} has started', preheaderTemplate: 'Recipients are being processed.', headlineTemplate: 'Campaign started', bodyTemplate: '<p>Outreach for <strong>{{campaign_name}}</strong> has begun.</p>', wired: false },
  { key: 'campaign_paused', family: 'outreach_campaigns', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'outreach', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: '{{campaign_name}} was paused', preheaderTemplate: 'Resume when ready.', headlineTemplate: 'Campaign paused', bodyTemplate: '<p><strong>{{campaign_name}}</strong> was paused.</p>', wired: false },
  { key: 'campaign_resumed', family: 'outreach_campaigns', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'outreach', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: '{{campaign_name}} resumed', preheaderTemplate: 'Sending continues.', headlineTemplate: 'Campaign resumed', bodyTemplate: '<p><strong>{{campaign_name}}</strong> is sending again.</p>', wired: false },
  { key: 'campaign_completed', family: 'outreach_campaigns', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'outreach', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: 'Your outreach campaign has finished', preheaderTemplate: '{{reply_count}} replies received.', headlineTemplate: 'Campaign completed', bodyTemplate: '<p><strong>{{campaign_name}}</strong> has finished sending.</p>', ctaLabel: 'View Campaign', wired: true, eventType: 'campaign.completed' },
  { key: 'campaign_partially_completed', family: 'outreach_campaigns', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'outreach', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: '{{campaign_name}} partially completed', preheaderTemplate: 'Some recipients could not be reached.', headlineTemplate: 'Campaign partially completed', bodyTemplate: '<p><strong>{{campaign_name}}</strong> finished with some delivery failures.</p>', ctaLabel: 'Review Results', wired: false },
  { key: 'campaign_failed', family: 'outreach_campaigns', communicationClass: 'business_notification', layoutFamily: 'failure', preferenceCategory: 'outreach', defaultPriority: 'critical', unsubscribePolicy: 'category', subjectTemplate: '{{campaign_name}} failed', preheaderTemplate: 'Review errors and retry.', headlineTemplate: 'Campaign failed', bodyTemplate: '<p><strong>{{campaign_name}}</strong> could not complete.</p>', ctaLabel: 'Review Campaign', wired: false },
  { key: 'prospect_replied', family: 'outreach_campaigns', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'outreach', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: '{{lead_name}} replied to your email', preheaderTemplate: 'From campaign: {{campaign_name}}.', headlineTemplate: 'Prospect replied', bodyTemplate: '<p><strong>{{lead_name}}</strong> replied to your outreach.</p>', ctaLabel: 'View Reply', wired: false },
  { key: 'outreach_daily_performance_report', family: 'outreach_campaigns', communicationClass: 'digest', layoutFamily: 'morning_brief', preferenceCategory: 'reports_outreach', defaultPriority: 'low', unsubscribePolicy: 'category', subjectTemplate: 'Outreach performance — {{reply_count}} replies today', preheaderTemplate: 'Daily campaign metrics.', headlineTemplate: 'Outreach daily report', bodyTemplate: '<p>Today\'s outreach sends, opens, and replies.</p>', wired: false },
];

const EMAIL_COMMUNICATION: PurposeSeed[] = [
  { key: 'email_sent', family: 'email_communication', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'email_activity', defaultPriority: 'low', unsubscribePolicy: 'category', subjectTemplate: 'Email sent successfully', preheaderTemplate: 'Delivery confirmed.', headlineTemplate: 'Email sent', bodyTemplate: '<p>Your email was sent successfully.</p>', wired: false },
  { key: 'email_delivery_failed', family: 'email_communication', communicationClass: 'business_notification', layoutFamily: 'failure', preferenceCategory: 'email_activity', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: 'Email delivery failed', preheaderTemplate: 'Review recipient and retry.', headlineTemplate: 'Delivery failed', bodyTemplate: '<p>An email could not be delivered.</p>', wired: false },
  { key: 'email_bounced', family: 'email_communication', communicationClass: 'business_notification', layoutFamily: 'failure', preferenceCategory: 'email_activity', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: 'Email bounced — {{email}}', preheaderTemplate: 'Address added to suppression list.', headlineTemplate: 'Email bounced', bodyTemplate: '<p>An email to <strong>{{email}}</strong> bounced permanently.</p>', wired: true, eventType: 'email.bounced' },
  { key: 'email_reply_received', family: 'email_communication', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'email_activity', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: 'New reply from {{lead_name}}', preheaderTemplate: 'Review in your unified inbox.', headlineTemplate: 'Reply received', bodyTemplate: '<p><strong>{{lead_name}}</strong> replied to your email.</p>', ctaLabel: 'Open Inbox', wired: false },
  { key: 'scheduled_email_sent', family: 'email_communication', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'email_activity', defaultPriority: 'low', unsubscribePolicy: 'category', subjectTemplate: 'Scheduled email sent', preheaderTemplate: 'Delivered on schedule.', headlineTemplate: 'Scheduled email sent', bodyTemplate: '<p>Your scheduled email was sent.</p>', wired: false },
  { key: 'scheduled_email_failed', family: 'email_communication', communicationClass: 'business_notification', layoutFamily: 'failure', preferenceCategory: 'email_activity', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: 'Scheduled email failed', preheaderTemplate: 'Review and reschedule.', headlineTemplate: 'Scheduled email failed', bodyTemplate: '<p>A scheduled email could not be sent.</p>', wired: false },
  { key: 'bulk_send_completed', family: 'email_communication', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'email_activity', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: 'Bulk send completed', preheaderTemplate: '{{lead_count}} messages processed.', headlineTemplate: 'Bulk send completed', bodyTemplate: '<p>Your bulk email send has completed.</p>', wired: false },
  { key: 'bulk_send_partially_failed', family: 'email_communication', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'email_activity', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: 'Bulk send partially failed', preheaderTemplate: 'Some recipients were not reached.', headlineTemplate: 'Bulk send partial failure', bodyTemplate: '<p>Some recipients in your bulk send could not be reached.</p>', wired: false },
  { key: 'recipient_unsubscribed', family: 'email_communication', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'email_activity', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: 'Recipient unsubscribed', preheaderTemplate: '{{email}} opted out of marketing.', headlineTemplate: 'Recipient unsubscribed', bodyTemplate: '<p>A recipient unsubscribed from marketing emails.</p>', wired: true, eventType: 'email.unsubscribed' },
  { key: 'sender_reputation_warning', family: 'email_communication', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'email_activity', defaultPriority: 'critical', unsubscribePolicy: 'category', subjectTemplate: 'Sender reputation warning', preheaderTemplate: 'Review bounce and complaint rates.', headlineTemplate: 'Sender reputation warning', bodyTemplate: '<p>Your sender reputation needs attention to maintain deliverability.</p>', ctaLabel: 'Review Settings', wired: false },
];

const SALES_PROPOSALS: PurposeSeed[] = [
  { key: 'proposal_created', family: 'sales_proposals', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'sales_proposals', defaultPriority: 'low', unsubscribePolicy: 'category', subjectTemplate: 'Proposal created for {{client_name}}', preheaderTemplate: 'Review before sending.', headlineTemplate: 'Proposal created', bodyTemplate: '<p>A new proposal for <strong>{{client_name}}</strong> was created.</p>', wired: false },
  { key: 'proposal_sent', family: 'sales_proposals', communicationClass: 'transactional', layoutFamily: 'light', preferenceCategory: 'sales_proposals', defaultPriority: 'normal', unsubscribePolicy: 'none', subjectTemplate: 'Proposal sent to {{client_name}}', preheaderTemplate: 'Awaiting client review.', headlineTemplate: 'Proposal sent', bodyTemplate: '<p>Your proposal was sent to <strong>{{client_name}}</strong>.</p>', wired: false },
  { key: 'proposal_viewed', family: 'sales_proposals', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'sales_proposals', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: '{{client_name}} viewed your proposal', preheaderTemplate: 'They may be ready to respond.', headlineTemplate: 'Proposal viewed', bodyTemplate: '<p><strong>{{client_name}}</strong> opened your proposal.</p>', ctaLabel: 'View Proposal', wired: false },
  { key: 'proposal_accepted', family: 'sales_proposals', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'sales_proposals', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: '{{client_name}} accepted your proposal', preheaderTemplate: 'Deal value: {{deal_value}}.', headlineTemplate: 'Proposal accepted', bodyTemplate: '<p><strong>{{client_name}}</strong> accepted your proposal.</p>', wired: false },
  { key: 'proposal_rejected', family: 'sales_proposals', communicationClass: 'business_notification', layoutFamily: 'failure', preferenceCategory: 'sales_proposals', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: '{{client_name}} declined your proposal', preheaderTemplate: 'Review feedback and follow up.', headlineTemplate: 'Proposal rejected', bodyTemplate: '<p><strong>{{client_name}}</strong> declined your proposal.</p>', wired: false },
  { key: 'proposal_expiring', family: 'sales_proposals', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'sales_proposals', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: 'Proposal expiring soon — {{client_name}}', preheaderTemplate: 'Follow up before it expires.', headlineTemplate: 'Proposal expiring', bodyTemplate: '<p>Your proposal for <strong>{{client_name}}</strong> expires soon.</p>', wired: false },
  { key: 'contract_generated', family: 'sales_proposals', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'contracts', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: 'Contract generated for {{client_name}}', preheaderTemplate: 'Ready for review and send.', headlineTemplate: 'Contract generated', bodyTemplate: '<p>A contract for <strong>{{client_name}}</strong> was generated.</p>', wired: false },
  { key: 'contract_sent', family: 'sales_proposals', communicationClass: 'transactional', layoutFamily: 'light', preferenceCategory: 'contracts', defaultPriority: 'normal', unsubscribePolicy: 'none', subjectTemplate: 'Contract sent to {{client_name}}', preheaderTemplate: 'Awaiting signature.', headlineTemplate: 'Contract sent', bodyTemplate: '<p>Your contract was sent to <strong>{{client_name}}</strong>.</p>', wired: false },
  { key: 'contract_signed', family: 'sales_proposals', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'contracts', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: '{{client_name}} signed your contract', preheaderTemplate: 'Agreement is now active.', headlineTemplate: 'Contract signed', bodyTemplate: '<p><strong>{{client_name}}</strong> signed your contract.</p>', ctaLabel: 'View Contract', wired: false },
  { key: 'contract_expiring', family: 'sales_proposals', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'contracts', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: 'Contract expiring — {{client_name}}', preheaderTemplate: 'Renewal may be required.', headlineTemplate: 'Contract expiring', bodyTemplate: '<p>The contract with <strong>{{client_name}}</strong> expires soon.</p>', wired: false },
];

const INVOICES_MONEY: PurposeSeed[] = [
  { key: 'invoice_created', family: 'invoices_money', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'invoices_payments', defaultPriority: 'low', unsubscribePolicy: 'category', subjectTemplate: 'Invoice #{{invoice_number}} created', preheaderTemplate: 'Amount: {{invoice_amount}}.', headlineTemplate: 'Invoice created', bodyTemplate: '<p>Invoice <strong>#{{invoice_number}}</strong> for {{invoice_amount}} was created.</p>', wired: false },
  { key: 'invoice_sent', family: 'invoices_money', communicationClass: 'transactional', layoutFamily: 'light', preferenceCategory: 'invoices_payments', defaultPriority: 'normal', unsubscribePolicy: 'none', subjectTemplate: 'Invoice #{{invoice_number}} sent', preheaderTemplate: 'Sent to {{client_name}}.', headlineTemplate: 'Invoice sent', bodyTemplate: '<p>Invoice <strong>#{{invoice_number}}</strong> was sent to {{client_name}}.</p>', wired: false },
  { key: 'invoice_viewed', family: 'invoices_money', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'invoices_payments', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: '{{client_name}} viewed invoice #{{invoice_number}}', preheaderTemplate: 'They may be preparing payment.', headlineTemplate: 'Invoice viewed', bodyTemplate: '<p><strong>{{client_name}}</strong> viewed invoice #{{invoice_number}}.</p>', wired: false },
  { key: 'invoice_due_soon', family: 'invoices_money', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'invoices_payments', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: 'Invoice #{{invoice_number}} due soon', preheaderTemplate: '{{invoice_amount}} due from {{client_name}}.', headlineTemplate: 'Invoice due soon', bodyTemplate: '<p>Invoice <strong>#{{invoice_number}}</strong> is due soon.</p>', wired: false },
  { key: 'invoice_overdue', family: 'invoices_money', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'invoices_payments', defaultPriority: 'critical', unsubscribePolicy: 'category', subjectTemplate: 'Invoice #{{invoice_number}} is overdue', preheaderTemplate: '{{invoice_amount}} outstanding from {{client_name}}.', headlineTemplate: 'Invoice overdue', bodyTemplate: '<p>Invoice <strong>#{{invoice_number}}</strong> for {{client_name}} is overdue.</p>', ctaLabel: 'View Invoice', wired: true, eventType: 'invoice.overdue' },
  { key: 'invoice_paid', family: 'invoices_money', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'invoices_payments', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: 'Invoice #{{invoice_number}} has been paid', preheaderTemplate: '{{invoice_amount}} received from {{client_name}}.', headlineTemplate: 'Invoice paid', bodyTemplate: '<p>Invoice <strong>#{{invoice_number}}</strong> to {{client_name}} was paid.</p>', ctaLabel: 'View Invoice', wired: false, eventType: 'invoice.paid' },
  { key: 'payment_received', family: 'invoices_money', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'invoices_payments', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: 'Payment received — {{invoice_amount}}', preheaderTemplate: 'From {{client_name}}.', headlineTemplate: 'Payment received', bodyTemplate: '<p>You received a payment of <strong>{{invoice_amount}}</strong> from {{client_name}}.</p>', wired: false },
  { key: 'payment_failed', family: 'invoices_money', communicationClass: 'business_notification', layoutFamily: 'failure', preferenceCategory: 'invoices_payments', defaultPriority: 'critical', unsubscribePolicy: 'category', subjectTemplate: 'Payment failed — {{client_name}}', preheaderTemplate: 'Review and retry collection.', headlineTemplate: 'Payment failed', bodyTemplate: '<p>A payment from <strong>{{client_name}}</strong> failed.</p>', wired: false },
  { key: 'payment_reminder', family: 'invoices_money', communicationClass: 'transactional', layoutFamily: 'light', preferenceCategory: 'invoices_payments', defaultPriority: 'normal', unsubscribePolicy: 'none', subjectTemplate: 'Payment reminder — Invoice #{{invoice_number}}', preheaderTemplate: '{{invoice_amount}} due.', headlineTemplate: 'Payment reminder', bodyTemplate: '<p>This is a reminder that invoice <strong>#{{invoice_number}}</strong> is due.</p>', wired: false },
  { key: 'monthly_finance_summary', family: 'invoices_money', communicationClass: 'digest', layoutFamily: 'morning_brief', preferenceCategory: 'reports_finance', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: 'Monthly finance summary', preheaderTemplate: 'Revenue, outstanding, and collections.', headlineTemplate: 'Monthly finance summary', bodyTemplate: '<p>Your monthly financial summary is ready.</p>', ctaLabel: 'View Finance', wired: false },
];

const CALENDAR_MEETINGS: PurposeSeed[] = [
  { key: 'meeting_booked', family: 'calendar_meetings', communicationClass: 'transactional', layoutFamily: 'success', preferenceCategory: 'meetings', defaultPriority: 'high', unsubscribePolicy: 'none', subjectTemplate: 'Meeting booked with {{client_name}}', preheaderTemplate: '{{meeting_time}}.', headlineTemplate: 'Meeting booked', bodyTemplate: '<p>A meeting with <strong>{{client_name}}</strong> was booked for {{meeting_time}}.</p>', ctaLabel: 'View Meeting', wired: false },
  { key: 'meeting_confirmation', family: 'calendar_meetings', communicationClass: 'transactional', layoutFamily: 'success', preferenceCategory: 'meetings', defaultPriority: 'normal', unsubscribePolicy: 'none', subjectTemplate: 'Meeting confirmed — {{meeting_time}}', preheaderTemplate: 'With {{client_name}}.', headlineTemplate: 'Meeting confirmed', bodyTemplate: '<p>Your meeting is confirmed for {{meeting_time}}.</p>', wired: false },
  { key: 'meeting_reminder', family: 'calendar_meetings', communicationClass: 'transactional', layoutFamily: 'light', preferenceCategory: 'meetings', defaultPriority: 'high', unsubscribePolicy: 'none', subjectTemplate: 'Reminder: meeting at {{meeting_time}}', preheaderTemplate: 'With {{client_name}}.', headlineTemplate: 'Meeting reminder', bodyTemplate: '<p>Your meeting with <strong>{{client_name}}</strong> is coming up.</p>', ctaLabel: 'View Meeting', wired: false },
  { key: 'meeting_starting_soon', family: 'calendar_meetings', communicationClass: 'transactional', layoutFamily: 'action_required', preferenceCategory: 'meetings', defaultPriority: 'critical', unsubscribePolicy: 'none', subjectTemplate: 'Meeting starting soon', preheaderTemplate: '{{client_name}} — {{meeting_time}}.', headlineTemplate: 'Meeting starting soon', bodyTemplate: '<p>Your meeting with <strong>{{client_name}}</strong> starts shortly.</p>', ctaLabel: 'Join Meeting', wired: false },
  { key: 'meeting_rescheduled', family: 'calendar_meetings', communicationClass: 'transactional', layoutFamily: 'action_required', preferenceCategory: 'meetings', defaultPriority: 'high', unsubscribePolicy: 'none', subjectTemplate: 'Meeting rescheduled — {{meeting_time}}', preheaderTemplate: 'With {{client_name}}.', headlineTemplate: 'Meeting rescheduled', bodyTemplate: '<p>Your meeting with <strong>{{client_name}}</strong> was rescheduled to {{meeting_time}}.</p>', wired: false },
  { key: 'meeting_cancelled', family: 'calendar_meetings', communicationClass: 'transactional', layoutFamily: 'failure', preferenceCategory: 'meetings', defaultPriority: 'high', unsubscribePolicy: 'none', subjectTemplate: 'Meeting cancelled', preheaderTemplate: 'With {{client_name}}.', headlineTemplate: 'Meeting cancelled', bodyTemplate: '<p>Your meeting with <strong>{{client_name}}</strong> was cancelled.</p>', wired: false },
  { key: 'booking_received', family: 'calendar_meetings', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'meetings', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: 'New booking from {{client_name}}', preheaderTemplate: '{{meeting_time}}.', headlineTemplate: 'Booking received', bodyTemplate: '<p><strong>{{client_name}}</strong> booked a meeting.</p>', wired: false },
  { key: 'booking_declined', family: 'calendar_meetings', communicationClass: 'business_notification', layoutFamily: 'failure', preferenceCategory: 'meetings', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: 'Booking declined', preheaderTemplate: '{{client_name}} could not meet.', headlineTemplate: 'Booking declined', bodyTemplate: '<p>A booking request was declined.</p>', wired: false },
  { key: 'follow_up_after_meeting', family: 'calendar_meetings', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'meetings', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: 'Follow up after meeting with {{client_name}}', preheaderTemplate: 'Send notes or next steps.', headlineTemplate: 'Post-meeting follow-up', bodyTemplate: '<p>Follow up with <strong>{{client_name}}</strong> after your recent meeting.</p>', wired: false },
  { key: 'daily_meeting_agenda', family: 'calendar_meetings', communicationClass: 'digest', layoutFamily: 'morning_brief', preferenceCategory: 'meetings', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: 'Your meeting agenda for today', preheaderTemplate: 'Scheduled meetings and prep items.', headlineTemplate: 'Daily meeting agenda', bodyTemplate: '<p>Your meetings and preparation items for today.</p>', ctaLabel: 'View Calendar', wired: false },
];

const SOCIAL_MARKETING: PurposeSeed[] = [
  { key: 'social_post_scheduled', family: 'social_marketing', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'social', defaultPriority: 'low', unsubscribePolicy: 'category', subjectTemplate: 'Social post scheduled', preheaderTemplate: 'Will publish automatically.', headlineTemplate: 'Post scheduled', bodyTemplate: '<p>Your social post was scheduled.</p>', wired: false },
  { key: 'social_post_published', family: 'social_marketing', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'social', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: 'Social post published', preheaderTemplate: 'Live on your connected channel.', headlineTemplate: 'Post published', bodyTemplate: '<p>Your social post was published successfully.</p>', wired: false },
  { key: 'social_publishing_failed', family: 'social_marketing', communicationClass: 'business_notification', layoutFamily: 'failure', preferenceCategory: 'social', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: 'Social post could not be published', preheaderTemplate: 'Review and retry.', headlineTemplate: 'Publishing failed', bodyTemplate: '<p>Your social post could not be published.</p>', ctaLabel: 'Review Post', wired: true, eventType: 'social.publish_failed' },
  { key: 'linkedin_connection_problem', family: 'social_marketing', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'integrations', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: 'Your LinkedIn connection needs attention', preheaderTemplate: 'Reconnect to resume publishing.', headlineTemplate: 'LinkedIn connection problem', bodyTemplate: '<p>Your LinkedIn integration needs to be reconnected.</p>', ctaLabel: 'Reconnect LinkedIn', wired: false },
  { key: 'facebook_connection_problem', family: 'social_marketing', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'integrations', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: 'Your Facebook connection needs attention', preheaderTemplate: 'Reconnect to resume publishing.', headlineTemplate: 'Facebook connection problem', bodyTemplate: '<p>Your Facebook integration needs to be reconnected.</p>', ctaLabel: 'Reconnect Facebook', wired: false },
  { key: 'instagram_connection_problem', family: 'social_marketing', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'integrations', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: 'Your Instagram connection needs attention', preheaderTemplate: 'Reconnect to resume publishing.', headlineTemplate: 'Instagram connection problem', bodyTemplate: '<p>Your Instagram integration needs to be reconnected.</p>', ctaLabel: 'Reconnect Instagram', wired: false },
  { key: 'campaign_performance_update', family: 'social_marketing', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'marketing', defaultPriority: 'low', unsubscribePolicy: 'category', subjectTemplate: 'Campaign performance update', preheaderTemplate: 'Latest engagement metrics.', headlineTemplate: 'Campaign performance', bodyTemplate: '<p>Your marketing campaign performance was updated.</p>', wired: false },
  { key: 'marketing_milestone', family: 'social_marketing', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'marketing', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: 'Marketing milestone reached', preheaderTemplate: 'Celebrate your progress.', headlineTemplate: 'Marketing milestone', bodyTemplate: '<p>You reached a marketing milestone.</p>', wired: false },
  { key: 'content_approval_required', family: 'social_marketing', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'marketing', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: 'Content approval required', preheaderTemplate: 'Review before publishing.', headlineTemplate: 'Approval required', bodyTemplate: '<p>Content is waiting for your approval before publishing.</p>', ctaLabel: 'Review Content', wired: false },
  { key: 'weekly_social_performance_report', family: 'social_marketing', communicationClass: 'digest', layoutFamily: 'morning_brief', preferenceCategory: 'reports_marketing', defaultPriority: 'low', unsubscribePolicy: 'category', subjectTemplate: 'Weekly social performance report', preheaderTemplate: 'Posts, reach, and engagement.', headlineTemplate: 'Weekly social report', bodyTemplate: '<p>Your weekly social media performance summary.</p>', wired: false },
];

const MCP_AUTOMATION: PurposeSeed[] = [
  { key: 'mcp_action_completed', family: 'mcp_automation', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'mcp_automation', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: 'Bonnie completed an action', preheaderTemplate: 'Review results in your workspace.', headlineTemplate: 'Action completed', bodyTemplate: '<p>An MCP action completed successfully.</p>', wired: true, eventType: 'mcp.action_completed' },
  { key: 'mcp_bulk_operation_completed', family: 'mcp_automation', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'mcp_automation', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: 'Bonnie finished your bulk operation', preheaderTemplate: 'Requested: {{lead_count}} · Processed successfully.', headlineTemplate: 'Bulk operation completed', bodyTemplate: '<p>Your bulk MCP operation has completed.</p>', ctaLabel: 'View Results', wired: true, eventType: 'mcp.bulk_completed' },
  { key: 'mcp_partial_failure', family: 'mcp_automation', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'mcp_automation', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: 'Bonnie completed with some failures', preheaderTemplate: 'Review partial results.', headlineTemplate: 'Partial failure', bodyTemplate: '<p>Your MCP operation completed with some failures.</p>', ctaLabel: 'Review Results', wired: true, eventType: 'mcp.partial_failure' },
  { key: 'mcp_operation_failed', family: 'mcp_automation', communicationClass: 'business_notification', layoutFamily: 'failure', preferenceCategory: 'mcp_automation', defaultPriority: 'critical', unsubscribePolicy: 'category', subjectTemplate: 'MCP operation failed', preheaderTemplate: 'Review error details.', headlineTemplate: 'Operation failed', bodyTemplate: '<p>An MCP operation failed and needs your attention.</p>', ctaLabel: 'View Details', wired: true, eventType: 'mcp.action_failed' },
  { key: 'bonnie_task_completed', family: 'mcp_automation', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'bonnie_activity', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: 'Bonnie completed a task', preheaderTemplate: 'Review in your workspace.', headlineTemplate: 'Task completed', bodyTemplate: '<p>Bonnie completed a task in your workspace.</p>', wired: false },
  { key: 'bonnie_requires_input', family: 'mcp_automation', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'bonnie_activity', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: 'Bonnie needs your input', preheaderTemplate: 'An action is waiting for approval.', headlineTemplate: 'Input required', bodyTemplate: '<p>Bonnie needs your input to continue.</p>', ctaLabel: 'Respond', wired: false },
  { key: 'automation_started', family: 'mcp_automation', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'automation', defaultPriority: 'low', unsubscribePolicy: 'category', subjectTemplate: 'Automation started', preheaderTemplate: 'Processing in the background.', headlineTemplate: 'Automation started', bodyTemplate: '<p>An automation workflow has started.</p>', wired: false },
  { key: 'automation_completed', family: 'mcp_automation', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'automation', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: 'Automation completed', preheaderTemplate: 'Review results.', headlineTemplate: 'Automation completed', bodyTemplate: '<p>Your automation workflow completed.</p>', wired: false },
  { key: 'automation_failed', family: 'mcp_automation', communicationClass: 'business_notification', layoutFamily: 'failure', preferenceCategory: 'automation', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: 'Automation failed', preheaderTemplate: 'Review and retry.', headlineTemplate: 'Automation failed', bodyTemplate: '<p>An automation workflow failed.</p>', ctaLabel: 'View Details', wired: false },
  { key: 'daily_ai_mcp_activity_report', family: 'mcp_automation', communicationClass: 'digest', layoutFamily: 'morning_brief', preferenceCategory: 'mcp_automation', defaultPriority: 'low', unsubscribePolicy: 'category', subjectTemplate: 'Daily AI/MCP activity report', preheaderTemplate: 'Bonnie completed {{lead_count}} actions today.', headlineTemplate: 'Daily MCP activity', bodyTemplate: '<p>Summary of Bonnie and MCP activity today.</p>', wired: false },
];

const PLATFORM_INTEGRATIONS: PurposeSeed[] = [
  { key: 'integration_connected', family: 'platform_integrations', communicationClass: 'business_notification', layoutFamily: 'success', preferenceCategory: 'integrations', defaultPriority: 'normal', unsubscribePolicy: 'category', subjectTemplate: 'Integration connected', preheaderTemplate: 'Your workspace is more connected.', headlineTemplate: 'Integration connected', bodyTemplate: '<p>A new integration was connected to your workspace.</p>', wired: false },
  { key: 'integration_disconnected', family: 'platform_integrations', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'integrations', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: 'Integration disconnected', preheaderTemplate: 'Reconnect to restore functionality.', headlineTemplate: 'Integration disconnected', bodyTemplate: '<p>An integration was disconnected from your workspace.</p>', ctaLabel: 'Reconnect', wired: false },
  { key: 'integration_token_expiring', family: 'platform_integrations', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'integrations', defaultPriority: 'high', unsubscribePolicy: 'category', subjectTemplate: 'Integration token expiring soon', preheaderTemplate: 'Reconnect before access is lost.', headlineTemplate: 'Token expiring', bodyTemplate: '<p>An integration token is expiring soon.</p>', ctaLabel: 'Reconnect', wired: false },
  { key: 'integration_reconnection_required', family: 'platform_integrations', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'integrations', defaultPriority: 'critical', unsubscribePolicy: 'category', subjectTemplate: 'Reconnection required', preheaderTemplate: 'An integration stopped working.', headlineTemplate: 'Reconnection required', bodyTemplate: '<p>An integration requires reconnection to continue working.</p>', ctaLabel: 'Reconnect', wired: false },
  { key: 'platform_maintenance', family: 'platform_integrations', communicationClass: 'transactional', layoutFamily: 'security', preferenceCategory: 'platform_announcements', defaultPriority: 'high', unsubscribePolicy: 'none', subjectTemplate: 'Scheduled platform maintenance', preheaderTemplate: 'Planned downtime notification.', headlineTemplate: 'Platform maintenance', bodyTemplate: '<p>AlphaClone will undergo scheduled maintenance.</p>', wired: false },
  { key: 'important_platform_update', family: 'platform_integrations', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'platform_announcements', defaultPriority: 'normal', unsubscribePolicy: 'global_marketing', subjectTemplate: 'Important platform update', preheaderTemplate: 'New features and improvements.', headlineTemplate: 'Platform update', bodyTemplate: '<p>An important update is available in AlphaClone.</p>', wired: false },
  { key: 'inactivity_3_day', family: 'platform_integrations', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'retention', defaultPriority: 'low', unsubscribePolicy: 'global_marketing', subjectTemplate: 'Your workspace misses you', preheaderTemplate: 'See what happened while you were away.', headlineTemplate: 'We miss you', bodyTemplate: '<p>It\'s been a few days — here\'s what\'s waiting in your workspace.</p>', ctaLabel: 'Open Workspace', wired: true, eventType: 'retention.inactivity_3d' },
  { key: 'inactivity_7_day', family: 'platform_integrations', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'retention', defaultPriority: 'normal', unsubscribePolicy: 'global_marketing', subjectTemplate: '7 days away — your business brief', preheaderTemplate: 'Leads, replies, and invoices waiting.', headlineTemplate: 'Your business is moving', bodyTemplate: '<p>While you were away, your business kept moving. See what needs attention.</p>', ctaLabel: 'Open Workspace', wired: true, eventType: 'retention.inactivity_7d' },
  { key: 'inactivity_14_day', family: 'platform_integrations', communicationClass: 'business_notification', layoutFamily: 'action_required', preferenceCategory: 'retention', defaultPriority: 'normal', unsubscribePolicy: 'global_marketing', subjectTemplate: '14 days — don\'t miss important updates', preheaderTemplate: 'Overdue invoices and pending replies.', headlineTemplate: 'Important updates waiting', bodyTemplate: '<p>Important business updates are waiting in your workspace.</p>', ctaLabel: 'Open Workspace', wired: true, eventType: 'retention.inactivity_14d' },
  { key: 'reactivation_30_day', family: 'platform_integrations', communicationClass: 'business_notification', layoutFamily: 'welcome', preferenceCategory: 'retention', defaultPriority: 'normal', unsubscribePolicy: 'global_marketing', subjectTemplate: 'Welcome back to AlphaClone', preheaderTemplate: 'Your workspace is ready when you are.', headlineTemplate: 'Welcome back', bodyTemplate: '<p>Your AlphaClone workspace is ready. Pick up where you left off.</p>', ctaLabel: 'Open Workspace', wired: true, eventType: 'retention.reactivation_30d' },
];

export const EMAIL_PURPOSE_REGISTRY: Record<string, EmailPurposeDefinition> = definePurposes([
  ...ACCOUNT_AUTH,
  ...ONBOARDING,
  ...BUSINESS_INTELLIGENCE,
  ...CRM_LEADS,
  ...OUTREACH_CAMPAIGNS,
  ...EMAIL_COMMUNICATION,
  ...SALES_PROPOSALS,
  ...INVOICES_MONEY,
  ...CALENDAR_MEETINGS,
  ...SOCIAL_MARKETING,
  ...MCP_AUTOMATION,
  ...PLATFORM_INTEGRATIONS,
]);

export function getEmailPurpose(templateKey: string): EmailPurposeDefinition | null {
  return EMAIL_PURPOSE_REGISTRY[templateKey] || null;
}

export function listEmailPurposes(filter?: { family?: EmailPurposeFamily; wired?: boolean }): EmailPurposeDefinition[] {
  return Object.values(EMAIL_PURPOSE_REGISTRY).filter((purpose) => {
    if (filter?.family && purpose.family !== filter.family) return false;
    if (filter?.wired !== undefined && purpose.wired !== filter.wired) return false;
    return true;
  });
}

export function resolvePurposeByEventType(eventType: string): EmailPurposeDefinition | null {
  return Object.values(EMAIL_PURPOSE_REGISTRY).find((p) => p.eventType === eventType) || null;
}

export function countEmailPurposes(): { total: number; wired: number; unwired: number } {
  const all = Object.values(EMAIL_PURPOSE_REGISTRY);
  const wired = all.filter((p) => p.wired).length;
  return { total: all.length, wired, unwired: all.length - wired };
}

/** Preference categories exposed in the preference center */
export const EMAIL_PREFERENCE_CATEGORIES = [
  { key: 'crm_leads', label: 'CRM & Leads', description: 'New leads, replies, and follow-ups' },
  { key: 'crm_sales', label: 'Sales & Deals', description: 'Opportunities, deals won/lost' },
  { key: 'outreach', label: 'Outreach & Campaigns', description: 'Campaign status and prospect replies' },
  { key: 'invoices_payments', label: 'Invoices & Payments', description: 'Invoice and payment notifications' },
  { key: 'contracts', label: 'Contracts', description: 'Contract status updates' },
  { key: 'meetings', label: 'Meetings & Calendar', description: 'Bookings and meeting reminders' },
  { key: 'mcp_automation', label: 'MCP & Automation', description: 'Bonnie and MCP operation results' },
  { key: 'bonnie_activity', label: 'Bonnie Activity', description: 'Tasks requiring input' },
  { key: 'reports_morning_brief', label: 'Morning Business Brief', description: 'Daily morning summary' },
  { key: 'reports_weekly', label: 'Weekly Reports', description: 'Weekly business review' },
  { key: 'reports_eod', label: 'End-of-Day Reports', description: 'Daily wrap-up' },
  { key: 'reports_finance', label: 'Finance Reports', description: 'Revenue and finance summaries' },
  { key: 'social', label: 'Social Publishing', description: 'Post status and failures' },
  { key: 'integrations', label: 'Integrations', description: 'Connection problems and token expiry' },
  { key: 'platform_announcements', label: 'Platform Announcements', description: 'Product updates' },
  { key: 'marketing', label: 'Marketing Updates', description: 'Tips, offers, and milestones' },
  { key: 'retention', label: 'Re-engagement', description: 'Inactivity reminders' },
] as const;
