-- ============================================================================
-- Bonnie Agentic OS Engine — Database Migration
-- 20260720220000_bonnie_agentic_os_engine.sql
--
-- Creates:
--   • bonnie_conversations  — one row per chat session (tenant + user scoped)
--   • bonnie_messages       — full message history with tool results & approval refs
--   • bonnie_workflows      — server-side execution records with state machine
--
-- Extends:
--   • autonomous_runner_approvals — adds edit_history JSONB column (non-breaking)
-- ============================================================================

BEGIN;

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. bonnie_conversations
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.bonnie_conversations (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id   UUID        NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    user_id     UUID        NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    title       TEXT        NOT NULL DEFAULT 'New conversation',
    module      TEXT        NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- One active conversation per user per tenant (most recent wins)
CREATE INDEX IF NOT EXISTS idx_bonnie_conversations_tenant_user
    ON public.bonnie_conversations (tenant_id, user_id, updated_at DESC);

ALTER TABLE public.bonnie_conversations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Tenant users can manage own conversations" ON public.bonnie_conversations;
CREATE POLICY "Tenant users can manage own conversations"
    ON public.bonnie_conversations
    FOR ALL
    USING (
        user_id = auth.uid()
        AND EXISTS (
            SELECT 1 FROM public.tenant_users tu
            WHERE tu.tenant_id = bonnie_conversations.tenant_id
              AND tu.user_id   = auth.uid()
        )
    )
    WITH CHECK (
        user_id = auth.uid()
        AND EXISTS (
            SELECT 1 FROM public.tenant_users tu
            WHERE tu.tenant_id = bonnie_conversations.tenant_id
              AND tu.user_id   = auth.uid()
        )
    );

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. bonnie_messages
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.bonnie_messages (
    id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id  UUID        NOT NULL REFERENCES public.bonnie_conversations(id) ON DELETE CASCADE,
    tenant_id        UUID        NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    user_id          UUID        NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    role             TEXT        NOT NULL CHECK (role IN ('user', 'assistant')),
    content          TEXT        NOT NULL DEFAULT '',
    -- Structured tool execution data
    tools            JSONB       NULL DEFAULT NULL,
    -- Reference to a pending approval that was generated by this message
    approval_id      UUID        NULL REFERENCES public.autonomous_runner_approvals(id) ON DELETE SET NULL,
    -- Execution state from the agent
    execution_status TEXT        NULL CHECK (
        execution_status IN (
            'executed', 'queued_for_approval', 'read_only_answer',
            'planning_failed', 'provider_blocked'
        )
    ),
    error            BOOLEAN     NOT NULL DEFAULT false,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bonnie_messages_conversation_created
    ON public.bonnie_messages (conversation_id, created_at ASC);

CREATE INDEX IF NOT EXISTS idx_bonnie_messages_tenant_created
    ON public.bonnie_messages (tenant_id, created_at DESC);

ALTER TABLE public.bonnie_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Tenant users can manage own messages" ON public.bonnie_messages;
CREATE POLICY "Tenant users can manage own messages"
    ON public.bonnie_messages
    FOR ALL
    USING (
        user_id = auth.uid()
        AND EXISTS (
            SELECT 1 FROM public.tenant_users tu
            WHERE tu.tenant_id = bonnie_messages.tenant_id
              AND tu.user_id   = auth.uid()
        )
    )
    WITH CHECK (
        user_id = auth.uid()
        AND EXISTS (
            SELECT 1 FROM public.tenant_users tu
            WHERE tu.tenant_id = bonnie_messages.tenant_id
              AND tu.user_id   = auth.uid()
        )
    );

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. bonnie_workflows
-- State machine: planning → running → waiting_for_approval → completed / failed
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.bonnie_workflows (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID        NULL REFERENCES public.bonnie_conversations(id) ON DELETE SET NULL,
    tenant_id       UUID        NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    user_id         UUID        NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    -- The original user instruction that triggered this workflow
    instruction     TEXT        NOT NULL,
    -- Current state machine status
    status          TEXT        NOT NULL DEFAULT 'planning' CHECK (
        status IN (
            'planning', 'running', 'waiting_for_approval',
            'completed', 'failed', 'cancelled'
        )
    ),
    -- Number of agent rounds executed
    rounds          INTEGER     NOT NULL DEFAULT 0,
    -- Full plan steps as produced by the agent (array of {id, label, tool, status})
    plan_steps      JSONB       NULL DEFAULT NULL,
    -- Complete tool results from all rounds
    tool_results    JSONB       NULL DEFAULT '[]'::jsonb,
    -- Execution logs from the agent
    logs            JSONB       NULL DEFAULT '[]'::jsonb,
    -- Retry/failure history
    retry_history   JSONB       NOT NULL DEFAULT '[]'::jsonb,
    -- Reference to the approval that is blocking this workflow (if any)
    blocking_approval_id UUID   NULL REFERENCES public.autonomous_runner_approvals(id) ON DELETE SET NULL,
    -- Final agent response
    final_response  TEXT        NULL,
    -- Execution status string from agent
    execution_status TEXT       NULL,
    -- Module context
    module          TEXT        NULL,
    started_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at    TIMESTAMPTZ NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bonnie_workflows_tenant_created
    ON public.bonnie_workflows (tenant_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_bonnie_workflows_conversation
    ON public.bonnie_workflows (conversation_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_bonnie_workflows_status
    ON public.bonnie_workflows (tenant_id, status, created_at DESC);

ALTER TABLE public.bonnie_workflows ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Tenant users can manage own workflows" ON public.bonnie_workflows;
CREATE POLICY "Tenant users can manage own workflows"
    ON public.bonnie_workflows
    FOR ALL
    USING (
        user_id = auth.uid()
        AND EXISTS (
            SELECT 1 FROM public.tenant_users tu
            WHERE tu.tenant_id = bonnie_workflows.tenant_id
              AND tu.user_id   = auth.uid()
        )
    )
    WITH CHECK (
        user_id = auth.uid()
        AND EXISTS (
            SELECT 1 FROM public.tenant_users tu
            WHERE tu.tenant_id = bonnie_workflows.tenant_id
              AND tu.user_id   = auth.uid()
        )
    );

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. Extend autonomous_runner_approvals with edit history
-- Non-breaking: ADD COLUMN IF NOT EXISTS
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE public.autonomous_runner_approvals
    ADD COLUMN IF NOT EXISTS edit_history JSONB NOT NULL DEFAULT '[]'::jsonb;

-- Index to make lookups by workflow fast
ALTER TABLE public.autonomous_runner_approvals
    ADD COLUMN IF NOT EXISTS workflow_id UUID NULL REFERENCES public.bonnie_workflows(id) ON DELETE SET NULL;

ALTER TABLE public.autonomous_runner_approvals
    ADD COLUMN IF NOT EXISTS conversation_id UUID NULL REFERENCES public.bonnie_conversations(id) ON DELETE SET NULL;

-- Source tracking (bonnie vs autonomous runner)
ALTER TABLE public.autonomous_runner_approvals
    ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'autonomous_runner';

CREATE INDEX IF NOT EXISTS idx_autonomous_runner_approvals_workflow
    ON public.autonomous_runner_approvals (workflow_id, created_at DESC)
    WHERE workflow_id IS NOT NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. Enable Realtime on approval center tables (so frontend can subscribe)
-- ─────────────────────────────────────────────────────────────────────────────

ALTER PUBLICATION supabase_realtime ADD TABLE public.autonomous_runner_approvals;
ALTER PUBLICATION supabase_realtime ADD TABLE public.bonnie_workflows;

COMMIT;
