import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {portalInvoiceBilling} from '../../src/lib/clientPortal/billing.ts';
import {storageReference,readStoredFile,readContractFile} from '../../src/lib/clientPortal/files.ts';
import {persistPortalMessage} from '../../src/lib/clientPortal/messages.ts';
import {loadClientProjects} from '../../src/lib/clientPortal/projects.ts';
import {portalOwnsResource} from '../../src/lib/auth/portalResourceOwnership.ts';
import {getClientFinancePortalData} from '../../src/services/finance/clientFinancePortalService.ts';

const tenant='11111111-1111-4111-8111-111111111111',client='22222222-2222-4222-8222-222222222222';
function database(tables={}) {
 const calls=[];
 const admin={calls,from(table){const filters=[];let single=false;let payload;let insertion=false;let max=Infinity;const q={
 select(){return q},eq(k,v){filters.push(r=>r[k]===v);calls.push([table,k,v]);return q},in(k,v){filters.push(r=>v.includes(r[k]));return q},is(k,v){filters.push(r=>(r[k]??null)===v);return q},gt(){return q},ilike(k,v){filters.push(r=>String(r[k]).toLowerCase()===v.toLowerCase());return q},filter(k,_op,v){const parts=k.split('->>');filters.push(r=>parts.length>1?r[parts[0]]?.[parts[1]]===v:r[k]===v);return q},or(){return q},contains(){return q},order(){return q},limit(v){max=v;return q},maybeSingle(){single=true;return q},single(){single=true;return q},insert(v){payload=v;insertion=true;return q},then(resolve,reject){try{let rows=tables[table]||[];if(insertion){if(rows.some(r=>r.id===payload.id))return Promise.resolve({data:null,error:{code:'23505'}}).then(resolve,reject);rows.push({...payload,created_at:new Date().toISOString()});tables[table]=rows;}const data=(insertion?rows.filter(r=>r.id===payload.id):rows.filter(r=>filters.every(f=>f(r)))).slice(0,max);return Promise.resolve({data:single?data[0]||null:data,error:null}).then(resolve,reject);}catch(e){return Promise.reject(e).then(resolve,reject);}}
 };return q;}};return admin;
}
test('partial balances use remaining amount, currency and overdue dates',()=>{const b=portalInvoiceBilling({total:1150,amount_paid:150,balance_due:1000,status:'sent',due_date:'2026-09-11',currency:'EUR',payment_link:'https://pay.example.com/a'},new Date('2026-10-09'));assert.equal(b.balanceDue,1000);assert.equal(b.status,'overdue');assert.equal(b.currency,'EUR');assert.equal(b.payable,true);});
test('harness evidence, pending payment and contradictory balances cannot demand payment',()=>{for(const i of [{invoice_number:'E2E-LIVE-1787911897',notes:'Live E2E harness'},{metadata:{payment_pending_confirmation:true}},{amount_paid:1150,balance_due:0}]){const b=portalInvoiceBilling({total:1150,status:'overdue',payment_link:'https://pay.example.com/a',...i});assert.ok(b.reviewReason);assert.equal(b.payable,false);assert.equal(b.paymentUrl,null);}});
test('no payment configuration is invented and unsafe links are rejected',()=>{for(const url of [undefined,'javascript:alert(1)','http://pay.example.com','https://user:pass@pay.example.com']){const b=portalInvoiceBilling({total:100,status:'sent',payment_link:url});assert.equal(b.paymentUrl,null);assert.equal(b.payable,false);}});
test('storage references reject external hosts and traversal',()=>{assert.equal(storageReference('https://evil.example/a.pdf','contracts','https://storage.example'),null);assert.equal(storageReference('../other/file.pdf'),null);assert.equal(storageReference('a/../b'),null);assert.deepEqual(storageReference('https://storage.example/storage/v1/object/public/contracts/tenant/file.pdf','documents','https://storage.example'),{bucket:'contracts',path:'tenant/file.pdf'});});
test('authentic stored bytes remain unchanged and integrity failures are surfaced',async()=>{const bytes=Buffer.from('%PDF-1.7\nauthentic signed bytes');const admin={storage:{from:()=>({download:async()=>({data:new Blob([bytes],{type:'application/pdf'}),error:null})})}};const file=await readStoredFile(admin,[{bucket:'contracts',path:'a.pdf'}],createHash('sha256').update(bytes).digest('hex'));assert.deepEqual(Buffer.from(file.bytes),bytes);await assert.rejects(readStoredFile(admin,[{bucket:'contracts',path:'a.pdf'}],'0'.repeat(64)),/INTEGRITY/);});
test('signed contracts resolve recorded references without regeneration',async()=>{const admin=database();const paths=[];admin.storage={from:bucket=>({download:async path=>{paths.push([bucket,path]);return {data:path==='original.pdf'?new Blob(['%PDF-authentic']):null,error:null};}})};const file=await readContractFile(admin,{id:'agreement',tenant_id:tenant,status:'fully_signed',pdf_url:'original.pdf'});assert.ok(file);assert.deepEqual(paths[0],['contracts','original.pdf']);admin.storage.from=()=>({download:async()=>({data:null,error:{code:'404'}})});assert.equal(await readContractFile(admin,{id:'missing',tenant_id:tenant,status:'fully_signed'}),null);});
test('project lookup merges legacy records, excludes other clients and hidden projects',async()=>{const admin=database({projects:[{id:'a',tenant_id:tenant,client_id:client},{id:'other',tenant_id:tenant,client_id:'other'},{id:'private',tenant_id:tenant,client_id:client,metadata:{client_visible:false}}],business_projects:[{id:'b',tenant_id:tenant,client_id:client},{id:'a',tenant_id:tenant,client_id:client}]});assert.deepEqual((await loadClientProjects(admin,tenant,client)).map(x=>x.id),['a','b']);});
test('ownership requires both tenant and client',()=>{const actor={tenantId:tenant,clientId:client};assert.equal(portalOwnsResource(actor,{id:'x',tenant_id:tenant,client_id:client}),true);for(const r of [null,{id:'x',tenant_id:'other',client_id:client},{id:'x',tenant_id:tenant,client_id:'other'}])assert.equal(portalOwnsResource(actor,r),false);});
test('persisted client message is visible to reply reader and retry does not duplicate',async()=>{const tables={};const admin=database(tables);const input={id:'request',tenantId:tenant,clientId:client,content:'Hello',authorName:'Fixture Client',isClient:true};assert.equal((await persistPortalMessage(admin,input)).replayed,false);assert.equal((await persistPortalMessage(admin,input)).replayed,true);assert.equal(tables.client_portal_events.length,1);assert.equal(tables.client_portal_events[0].metadata.content,'Hello');await assert.rejects(persistPortalMessage(admin,{...input,content:'Different'}),/already used/);await persistPortalMessage(admin,{...input,id:'reply',content:'Reply',isClient:false});assert.equal(tables.client_portal_events[1].metadata.is_client,false);});
test('project message retries remain scoped to one project',async()=>{const tables={};const admin=database(tables);const input={id:'request',tenantId:tenant,clientId:client,projectId:'project-a',content:'Hello',authorName:'Fixture Client',isClient:true};await persistPortalMessage(admin,input);assert.equal((await persistPortalMessage(admin,input)).replayed,true);assert.equal(tables.project_comments.length,1);await assert.rejects(persistPortalMessage(admin,{...input,projectId:'project-b'}));});
test('overview totals, billing warnings and activity match canonical records',async()=>{const admin=database({business_clients:[{id:client,tenant_id:tenant,name:'Fixture Client',finance_portal_token:'token',is_active:true}],tenants:[{id:tenant,name:'Fixture Business',settings:{}}],business_invoices:[{id:'usd',tenant_id:tenant,client_id:client,invoice_number:'INV-1',total:1150,amount_paid:150,balance_due:1000,status:'overdue',currency:'USD'},{id:'eur',tenant_id:tenant,client_id:client,invoice_number:'INV-2',total:200,balance_due:200,status:'sent',currency:'EUR'},{id:'harness',tenant_id:tenant,client_id:client,invoice_number:'E2E-LIVE-1',total:1150,balance_due:0,status:'overdue'}],workspace_activity:[{id:'event',tenant_id:tenant,client_id:client,event_type:'invoice.updated',summary:'Invoice updated',created_at:'2026-10-09T10:00:00Z'}]});const portal=await getClientFinancePortalData(admin,'token');assert.deepEqual(portal.summary.balancesByCurrency,{USD:1000,EUR:200});assert.equal(portal.summary.openInvoices,2);assert.equal(portal.summary.billingReviews,1);assert.equal(portal.activity[0].title,'Invoice updated');assert.ok(portal.invoices[0].viewUrl);assert.equal(portal.invoices[0].payUrl,null);});

test('invalid ledger values and inconsistent partial balances require review',()=>{for(const invoice of [{total:'invalid',balance_due:100},{total:100,amount_paid:20,balance_due:100},{total:100,currency:'invalid-code'}]){const b=portalInvoiceBilling({...invoice,status:'sent',payment_link:'https://pay.example.com'});assert.ok(b.reviewReason);assert.equal(b.payable,false);}});
test('activity excludes hidden projects and unshared or other-client resources',async()=>{const {getClientScopedActivity}=await import('../../src/services/finance/workspaceActivityService.ts');const admin=database({projects:[{id:'hidden',tenant_id:tenant,client_id:client,metadata:{client_visible:false}}],contracts:[{id:'draft',tenant_id:tenant,client_id:client,status:'draft'},{id:'shared',tenant_id:tenant,client_id:client,status:'signed'}],workspace_activity:[{id:'private',tenant_id:tenant,client_id:client,project_id:'hidden'},{id:'unshared',tenant_id:tenant,client_id:client,contract_id:'draft'},{id:'foreign',tenant_id:tenant,client_id:client,invoice_id:'other-client-invoice'},{id:'visible',tenant_id:tenant,client_id:client,contract_id:'shared'}]});const {activity}=await getClientScopedActivity(admin,tenant,client,{throwErrors:true});assert.deepEqual(activity.map(x=>x.id),['visible']);});
